### ISSUE TITLE
PackageExportsNameCheck - severity error

### ISSUE THREAD

**Issue by svilenvul** [openhab/static-code-analysis#100]
@kaikreuzer 

We are writing a check that will cover this guideline:

> 10. Packages that contain classes that are not meant to be used by other bundles should have “internal” in their package name.  

What severity should be used ? Warning or maybe just info ?

Many bundles (according to my estimation around 40-50 percent of the bundles ) in the OH2 addons repo  contain packages that are not exported but are not "internal". Most often that are packages x.y.z.config and x.y.z.discovery. How important is this naming convention - should we proceed with some clean up and how ?

**Comment by kaikreuzer** [comment]
I consider it very important - it imho should be a warning, if not even an error. We might even want to rephrase the guideline from "should" to "must". The easiest cleanup would be to add the package exports for everything that is not "internal" - although it would make sense to check the bindings to rather move stuff to internal packages.

@sjka, what is your position on that?

**Comment by sjka** [comment]
> The easiest cleanup would be to add the package exports for everything that is not "internal"

Not so cool. I'd rather like to avoid this. 

> although it would make sense to check the bindings to rather move stuff to internal packages.

Yes - more work, but much better.

> Packages MUST either be exported or contain "internal" 

I'm okay with that. 

Please make it at least a "warning", because it potentially is a mistake. By the way, in bndtools they do it similar: they create a warning (and don't package it into the jar 😉 ).  

"Error" would be fine by me too, but I also see the risk that this rather leads to broadening APIs instead of thinking about them. Also, error is not really necessary as the code will work nicely anyway. It's just not nice and against our convention.

**Comment by svilenvul** [comment]
OK, thanks for the clarification. 

I will try to rename the packages using the Eclipse IDE refactor options. As they are not exported, I guess (almost) no problems should occur as long as everything compiles . The only thing that comes to mind is that some .xml files in OSGI-INF should be modified to use the new class names ? WDYT ?
  
If we are going to clean the repo, I prefer to set the severity of the check to error :)

**Comment by maggu2810** [comment]
I personally export all packages except the ones that contains `internal` or `impl`. This is the default e.g. for the maven-bundle-plugin.
The bundle-maven-plugin does not follow this rule (in its default configuration).

---

There are also other opinions (http://njbartlett.name/2015/03/27/announcing-bnd-maven-plugin.html):

The second issue is that maven-bundle-plugin has some questionable features and design choices. For example it automatically exports all packages that do not contain the substrings “impl” or “internal”. The motivation was understandable at the time – it is closer to normal Java with all packages being implicitly exported – but this is really just wrong from a modularity point of view, and goes against OSGi best practices. The bnd-maven-plugin instead includes all packages from the project in the bundle but exports nothing by default. The developer must choose explicitly which packages are exported.

---

**Comment by svilenvul** [comment]
I have took a look at the openhab2 addons with violations and there are several cases. I plan to proceed the following way :
- packages that contain *config* or *discovery* could be renamed to *internal.config* and *internal.discovery* (and DS .xml files should be edited);
- packages that contain *handler* could be exported ( I guess there is some reason for exporting packages with handlers ?);
- some not exported packages contain interfaces used for service registration, they should be exported instead of renamed to make sure that now API breaking changes will occur. 

Do you agree with this approach ?

**Comment by martinvw** [comment]
Should we keep this one open to track making it an error?

**Comment by svilenvul** [comment]
@VelinYordanov can take a look at that.

**Comment by VelinYordanov** [comment]
I executed the static-code-analysis tool on the smarthome repository and found 28 packages that need refactoring as well.

**Comment by VelinYordanov** [comment]
@kaikreuzer I noticed that some of the packages are in sample bundles. Should a suppression be added for them?

**Comment by kaikreuzer** [comment]
> I noticed that some of the packages are in sample bundles. Should a suppression be added for them?

Not necessarily - especially samples should respect our guidelines, so unless you see that there is a good reason for them not to apply them, I would vote for fixing them as well.

**Comment by svilenvul** [comment]
I see the changes in the Loxone Binding are merged - https://github.com/openhab/openhab2-addons/pull/2786/commits, so we are waiting only for the Network binding :-)

**Comment by martinvw** [comment]
I started a rebuild of the network binding, if that is green I ll merge it and @cweitkamp can do the changes after the merge

**Comment by martinvw** [comment]
The network binding PR is merged

**Comment by svilenvul** [comment]
Great, thank you all !
