### ISSUE TITLE
Add a warning for JavaDocs that only use "inheritDoc"

### ISSUE THREAD

**Issue by kaikreuzer** [openhab/static-code-analysis#103]
I often see these in reviews:

```
   /**
    * {@inheritDoc}
    */
   @Override
```
e.g. [here](https://github.com/openhab/openhab2-addons/pull/2363/files#diff-7e55bfb77881a45bfe89e90c560e5187R137).

As Javadoc is inherited by default from an interface definition if nothing else is specified, this is redundant and should be avoided. I would therefore suggest to add a warning in such a case.

`inheritDoc` should imho only be used if some additional documentation is added to it on a specific method.

**Comment by svilenvul** [comment]
A similar proposal for check is made here https://github.com/sevntu-checkstyle/sevntu.checkstyle/issues/467
