### ISSUE TITLE
Is it possible to skip a check in external repository?

### ISSUE THREAD

**Issue by pfink** [openhab/static-code-analysis#104]
Since the update to openHAB 2.2, I'm getting the following build error for my binding (https://github.com/pfink/openhab2-flicbutton):

```
Wrong /project/parent/version in the pom.xml file. The version should match the one in the MANIFEST.MF file.
```

I think this check makes sense for the addons which are part of the official openhab2-addons repository, but it does not fit for addons outside this repo as those addons may not  have the same release cycle than openHAB and may don't want to use the same versions. From my point of view there should be a possibility to skip this rule without having to skip the whole static code analysis.

**Comment by martinvw** [comment]
We recently discussed this in the maintainers group for now everything will still have one version but in the future we might investigate letting this restriction go.

I think the problem place to start a discussion about that is https://github.com/openhab/openhab-core/issues

**Comment by svilenvul** [comment]
I think this is good point. The important question here is - "Is it possible to skip a check in external repository?" There are two options here:

- using a custom .xml file with rules description. I don't recommend this one, it will be hard to keep it up to date with the one in the static-code-analysis repository;
- overwrite the severity of a check in a properties file. This is less painful, but requires some changes in the [checkstyle rules file](https://github.com/openhab/static-code-analysis/blob/master/src/main/resources/rulesets/checkstyle/rules.xml). The downside is that this approach could be used only for checkstyle checks.

**Comment by pfink** [comment]
@martinvw: I'm not sure whether there is much to discuss here. Regardless of any discussions, external bindings will definitely often not have the same release cycle as openHAB and if the project tries to enforce this by checkstyle rules, those projects will have no other option than skipping the complete ruleset right now - and they will do so, just as I am doing it with my binding now.

So the question for me here is not whether this rule makes sense or not. If it's kept, people will begin to skip the whole ruleset as you cannot (and should not) enforce them to release their bindings only when openHAB wants it.

**Comment by martinvw** [comment]
> So the question for me here is not whether this rule makes sense or not. If it's kept, people will begin to skip the whole ruleset as you cannot enforce them to release their bindings only when openHAB wants it (especially in early development phases). So the question is more about: Do we want to have such strict rules that people are almost pushed to skip the whole stuff? Or: How to handle bindings which do not fit into the ruleset?

Fair point and definitely something to take a look at. Was this the only rule you walked into or where there also other problems?

Purely looking at the version rule maybe a proper split would be:

- the version in the manifest should match the version in the pom.xml if not error
- the version in the parent should match the version in the pom if not (warning or info for external versioned components, error for components part of the main repo)

However at this moment we can only configure severity per file containing multiple checks and it might have some performance impact to split rules up in individual files.

@svilenvul I suppose we can also use the following https://github.com/openhab/static-code-analysis/blob/master/docs/maven-plugin.md#customization with a `checkstyleFilter` which should be populated with a supression filter https://maven.apache.org/plugins/maven-checkstyle-plugin/examples/suppressions-filter.html 

Although I never tested this and have no time to do so now.

**Comment by pfink** [comment]
Sounds good! I did not walk into other rule issues yet.

**Comment by svilenvul** [comment]
This is an option too. Here is the filter that is used by default - https://github.com/openhab/static-code-analysis/blob/master/src/main/resources/rulesets/checkstyle/suppressions.xml.

Keep in mind that both can't be used at the same time.

**Comment by martinvw** [comment]
@pfink were you able to set this up or are you still ignoring the checks for now?

**Comment by pfink** [comment]
@martinvw: I know this is coming very late, but finally I was able building my flicbutton project again. I had to implement some changes to be compliant but there are no "evil" rules that I cannot fulfill anymore. So it's working fine now, don't have to skip it anymore :)

**Comment by martinvw** [comment]
Great thanks for checking it out!
