### ISSUE TITLE
FindBugs memory leak when same JVM is used

### ISSUE THREAD

**Issue by svilenvul** [openhab/static-code-analysis#111]
We have noticed that the static analysis tool is consuming a lot of memory when executed on a multi module build (as the openHAB build :)) and I made some research. I will try to summarize the results here.

I remember that we had a [discussion ](https://github.com/openhab/static-code-analysis/issues/15) if we should disable the fork option (which spawns a separate Java process for each execution of the FindBugs plugin), but this doesn't seem to be the best option now.

I have used the jconsole memory profiling tool and below can be seen the most critical leak that I have found (1 GB of non-heap memory usage):

![sat-non-heap](https://user-images.githubusercontent.com/7120104/28164676-1a1edb4e-67d9-11e7-8806-9595663bb7ae.PNG)

The memory seems to be consumed by 100 000 classes that are being loaded (the lower left window). I suspect that the problem is related to the fact that the same JVM is used (see below for more details): 

![sat](https://user-images.githubusercontent.com/7120104/28164936-5288ba3a-67da-11e7-95d6-064543b69e8e.PNG)

I have customized the build and excluding the FindBugs maven plugin the problem disappears. 

I have experimented again with a fork set to true and the results are good (non-heap memory usage is stable around 200 MB and 20 000 classes are loaded), the separate process consumes around 300 MB before dying:

![satfork-non-heap](https://user-images.githubusercontent.com/7120104/28166164-92fa7d56-67df-11e7-8dd2-2b1c285f4cbe.PNG)
![satfork](https://user-images.githubusercontent.com/7120104/28166171-996b2c62-67df-11e7-8a10-3dea6e3d3fd2.PNG)

@kaikreuzer, I think the best option will be to use a separate thread for FindBugs, but this change could directly affect the openHAB build. Please share your opinion on the topic :)

**Comment by kaikreuzer** [comment]
Not sure if I am missing any new facts in here, but as far as I can see, this is the same as my observations in #15, i.e. that findbugs causes the high memory consumption. When you fork a JVM, did you also measure the total memory footprint by both those JVMs? From my observations, it was better not to fork one as mentioned in https://github.com/openhab/static-code-analysis/issues/15#issuecomment-286754237: "the memory consumption IS less because there isn't a second JVM anymore"

**Comment by svilenvul** [comment]
> When you fork a JVM, did you also measure the total memory footprint by both those JVMs? 

It is living for only a few seconds, what I see from the system explorer - additional 300 MBs. So short term (during the first several modules build) it will consume more memory, but the average memory consumption and the peek one will be definitely less with the fork.

**Comment by kaikreuzer** [comment]
Ok, fair point. But please note that we initially had fork=true and I came across the issues because the 1GB memory on Cloudbees didn't suffice. So simply switching it back now, won't bring us any further. I guess what we need is a fix for the memory leak itself...

**Comment by svilenvul** [comment]
I have done a test using the SpotBugs Maven plugin in combination with SpotBugs and the results are  much better :) :

![spotbugs](https://user-images.githubusercontent.com/7120104/28260849-8a90c82e-6ae5-11e7-98b7-fa96bb27989d.PNG)

![spotbugs](https://user-images.githubusercontent.com/7120104/28260851-8f3a0cb4-6ae5-11e7-9969-93fdb937abca.PNG)

**Comment by kaikreuzer** [comment]
Sounds promising! Will test it on Cloudbees next week when I am back at my desk!

**Comment by kaikreuzer** [comment]
Hey @svilenvul! I have successfully tested the latest version and it looks all good - the build is successful and the memory consumption indeed looks much better now 👍 

If you agree, I would go ahead and build and deploy a new release.

**Comment by kaikreuzer** [comment]
New release is done: https://github.com/openhab/static-code-analysis/releases/tag/0.1.0
