### ISSUE TITLE
Add check for tabs in java files

### ISSUE THREAD

**Issue by kaikreuzer** [openhab/static-code-analysis#12]
Our code formatter is using spaces and no tabs in java files.
I'd therefore claim that any tab within a java file is not correct and should be marked as an error.

Could such a check be added?

**Comment by svilenvul** [comment]
Yes, this is the [FileTabCharacterCheck](https://github.com/openhab/static-code-analysis/blob/master/src/main/resources/rulesets/checkstyle/rules.xml#L17) and is already included

From the javadoc:
>Checks to see if a file contains a tab character.

The tool found a tab in the [AutelisBindingConstants](https://github.com/openhab/openhab2-addons/blob/50f7f662b4e5cf9f99b0c9a3e64f7097357d17e4/addons/binding/org.openhab.binding.autelis/src/main/java/org/openhab/binding/autelis/AutelisBindingConstants.java) and other classes in the autelis binding.

**Comment by kaikreuzer** [comment]
Ah, cool, thanks.

**Comment by kaikreuzer** [comment]
> ...and should be marked as an error.

This seems to be currently "priority 3", which I assume will not result in a failing build, right?
Is it possible to change the priority of single checks, i.e. increase this one to be an error?

**Comment by svilenvul** [comment]
Yes it can be changed and only priority 1 will fail the build.

Actually we haven't set any priority 1 issues now (only bugs found by FindBugs will fail the build now).

**Comment by kaikreuzer** [comment]
> Actually we haven't set any priority 1 issues now

So we should start with it.
Imho, everything that makes me ask for changes on a PR is also a candidate to fail the build (at least where no false positives can be expected).

And missing code formatter is definitely such a case.

> OK, I will go for it and prepare a PR for openhab2-addons too.

imho this can be part of the default rules, because the very same applies to ESH.

**Comment by svilenvul** [comment]
> OK, I will go for it and prepare a PR for openhab2-addons too

What I meant to say was that all tabs should be removed from the .java files in openhab2-addons in order to keep the build green.

**Comment by kaikreuzer** [comment]
Ah, right, even better :-)
