### ISSUE TITLE
Change the priority of HeaderCheck from info to error

### ISSUE THREAD

**Issue by svilenvul** [openhab/static-code-analysis#128]
> kaikreuzer 16 hours ago Owner

>Hm, I found out why: Because it is considered prio 3.
@svilenvul Did we do that by intention? I would actually hope that a missing header breaks the build - and where we have exceptions because we need different headers, it would be nice if we could deactivate this check in the pom of the appropriate bundle.

See https://github.com/openhab/openhab2-addons/pull/1711#discussion_r131113839

**Comment by svilenvul** [comment]
@kaikreuzer,

I am not sure which repositories this change might affect. For now the list should include:
- https://github.com/openhab/openhab-core
- https://github.com/openhab/openhab-distro
- https://github.com/openhab/openhab1-addons
- https://github.com/openhab/openhab2-addons

 It is really hard to manually build all these repositories and ensure that all exceptions are added, so the build won't be broken. 

Could we somehow automate this process? Build the affected repositories once a PR is opened ? Wdyt ?

**Comment by kaikreuzer** [comment]
No, there is no way to do that. The version of SAT is specified in openhab-core and the other repos will only get hold of it once this updated pom is deployed - we cannot do PR builds.

What you can leave out of the picture is openhab1-addons as this is configured to not fail in any case. Likewise openhab-distro: This does not contain any OSGi bundles, so the SAT tool is not relevant.

This makes a manual check not too hard:
Change openhab-core/poms/pom.xml and put in a snapshot version of SAT (which you have installed in your local maven repo). Do a `mvn install -N` of that file.
Now you can run the full build on openhab-core and openhab2-addons and can check the results.
