### ISSUE TITLE
Add checks for README.md

### ISSUE THREAD

**Issue by kaikreuzer** [openhab/static-code-analysis#13]
A very common mistake in PRs is that there are no empty lines in READMEs to make the Jekyll-rendering correct.

On https://www.eclipse.org/smarthome/documentation/development/bindings/docs.html, we have documented the rules:

> There must be an empty line after every header (#...).
> There must be an empty line before and after every list.
> There must be an empty line before and after every code section.

It would be great if this could be checked automatically on any README.md file.

Additionally, for bindings, the existence of a README.md file should be checked (and the build should fail, if none is there).

**Comment by svilenvul** [comment]
Thanks, this sounds like a really good idea :).

Additionally @petarnv is working on a check for missing files, but maybe he can give more details about it in a separate issue.

**Comment by petarnv** [comment]
An issue for implementing a check that verifies the existence of the "special" files is opened: https://github.com/openhab/static-code-analysis/issues/14

**Comment by doandzhi** [comment]
I started working on the check. Seems like it has to cover some specific cases but will do my best implementing it qualitatively.

**Comment by doandzhi** [comment]
@svilenvul Can you please add me as an assignee in order to proceed with the check?

**Comment by svilenvul** [comment]
I would like to, but it doesn't seems to be possible through the GitHub UI, really strange :)
