### ISSUE TITLE
Travis build and local build report differ with version 0.1.0

### ISSUE THREAD

**Issue by cweitkamp** [openhab/static-code-analysis#131]
>> [ERROR] ERROR found by checkstyle: .binding.avmfritz.test/META-INF/MANIFEST.MF:25 The MANIFEST.MF file must not contain any Require-Bundle entries. Instead, Import-Package must be used.
> 
> The "Require-Bundle" entries in the test fragment (for org.junit, org.mockito, org.hamcrest) are the only exception from this rule. We have to adopt this in the checkstyle configuration.

See openhab/openhab2-addons#2516 .

**Comment by svilenvul** [comment]
It is done: https://github.com/openhab/static-code-analysis/blob/master/src/main/resources/rulesets/checkstyle/suppressions.xml#L20, but I am not sure if it is included in the 0.1.0 release.

**Comment by svilenvul** [comment]
Hmm, actually it is, so I am surprised - https://github.com/openhab/static-code-analysis/milestone/7?closed=1

**Comment by cweitkamp** [comment]
Can I help you in any way?

**Comment by svilenvul** [comment]
I have just checked out your [branch](https://github.com/cweitkamp/openhab2-addons/tree/AVMFritzLocalizationJavaUnitTests) and build the test bundle successfully.

![avmfritz](https://user-images.githubusercontent.com/7120104/29060186-530b5c46-7c21-11e7-8bb8-9c2cbd899c75.png)

**Comment by cweitkamp** [comment]
Thanks for investigation. I am glad to hear you got it running. I cannot. What did I wrong? By the way. I opened a test PR with the same branch you try to build an Travis doesn't like it either: https://travis-ci.org/openhab/openhab2-addons/builds/262149216#L462

**Comment by svilenvul** [comment]
I don`t think that you did something wrong. :)

The only one thing that comes to my mind is that we are using two different jars with version 0.1.0.

I have deleted static-code-analysis-0.1.0.jar from my local maven repo and when I started the build I saw :

```
....
Downloading: https://jcenter.bintray.com/org/openhab/tools/static-code-analysis/0.1.0/static-code-analysis-0.1.0.pom
Downloaded: https://jcenter.bintray.com/org/openhab/tools/static-code-analysis/0.1.0/static-code-analysis-0.1.0.pom (8.7 kB at 3.8 kB/s)
Downloading: https://jcenter.bintray.com/org/openhab/tools/static-code-analysis/0.1.0/static-code-analysis-0.1.0.jar
Downloaded: https://jcenter.bintray.com/org/openhab/tools/static-code-analysis/0.1.0/static-code-analysis-0.1.0.jar (101 kB at 34 kB/s)
[WARNING] No explicit target runtime environment configuration. Build is platform dependent.
[INFO] Computing target platform for MavenProject: org.openhab.binding:org.openhab.binding.airquality:2.2.0-SNAPSHOT @ C:\prj\openHAB\EclipseIDE\git\openhab2-addons\addons\binding\org.openhab.binding.airquality\pom.xml
[INFO] Fetching p2.index from https://openhab.jfrog.io/openhab/eclipse-smarthome-stable/ (172B)
[INFO] Adding repository https://openhab.jfrog.io/openhab/eclipse-smarthome-stable
....
....
[INFO] --- static-code-analysis:0.1.0:checkstyle (default) @ org.openhab.binding.airquality ---
[INFO] Adding dependency to checkstyle:7.7
[INFO]
[INFO] --- static-code-analysis:0.1.0:pmd (default) @ org.openhab.binding.airquality ---
[INFO]
[INFO] --- static-code-analysis:0.1.0:findbugs (default) @ org.openhab.binding.airquality ---
[INFO] Adding dependency to spotbugs:3.1.0-RC3
[INFO] Adding dependency to bug-pattern:1.2.4
[INFO] Fork Value is false
     [java] JVM args ignored when same JVM is used.
[INFO] Done FindBugs Analysis....
....
```

which was expected.
In the log from Travis above I see something different:

```
...
[INFO] --- static-code-analysis:0.1.0:checkstyle (default) @ org.openhab.binding.airquality ---
[INFO] Downloading: https://jcenter.bintray.com/org/slf4j/slf4j-api/1.7.24/slf4j-api-1.7.24.pom
[INFO] Downloaded: https://jcenter.bintray.com/org/slf4j/slf4j-api/1.7.24/slf4j-api-1.7.24.pom (4 KB at 43.0 KB/sec)
[INFO] Downloading: https://jcenter.bintray.com/org/slf4j/slf4j-parent/1.7.24/slf4j-parent-1.7.24.pom
[INFO] Downloaded: https://jcenter.bintray.com/org/slf4j/slf4j-parent/1.7.24/slf4j-parent-1.7.24.pom (14 KB at 134.6 KB/sec)
[INFO] Downloading: https://jcenter.bintray.com/org/slf4j/slf4j-simple/1.7.24/slf4j-simple-1.7.24.pom
[INFO] Downloaded: https://jcenter.bintray.com/org/slf4j/slf4j-simple/1.7.24/slf4j-simple-1.7.24.pom (1015 B at 10.1 KB/sec)
[INFO] Downloading: https://jcenter.bintray.com/net/sourceforge/pmd/pmd-xml/5.5.1/pmd-xml-5.5.1.pom
[INFO] Downloaded: https://jcenter.bintray.com/net/sourceforge/pmd/pmd-xml/5.5.1/pmd-xml-5.5.1.pom (4 KB at 33.5 KB/sec)
[INFO] Downloading: https://jcenter.bintray.com/net/sourceforge/pmd/pmd/5.5.1/pmd-5.5.1.pom
[INFO] Downloaded: https://jcenter.bintray.com/net/sourceforge/pmd/pmd/5.5.1/pmd-5.5.1.pom (38 KB at 351.8 KB/sec)
[INFO] Downloading: https://jcenter.bintray.com/jaxen/jaxen/1.1.6/jaxen-1.1.6.pom
[INFO] Downloaded: https://jcenter.bintray.com/jaxen/jaxen/1.1.6/jaxen-1.1.6.pom (14 KB at 95.6 KB/sec)
[INFO] Downloading: https://jcenter.bintray.com/net/sourceforge/pmd/pmd-core/5.5.1/pmd-core-5.5.1.pom
[INFO] Downloaded: https://jcenter.bintray.com/net/sourceforge/pmd/pmd-core/5.5.1/pmd-core-5.5.1.pom (5 KB at 57.8 KB/sec)
[INFO] Downloading: https://jcenter.bintray.com/com/beust/jcommander/1.48/jcommander-1.48.pom
[INFO] Downloaded: https://jcenter.bintray.com/com/beust/jcommander/1.48/jcommander-1.48.pom (10 KB at 109.3 KB/sec)
[INFO] Downloading: https://jcenter.bintray.com/org/sonatype/oss/oss-parent/3/oss-parent-3.pom
[INFO] Downloaded: https://jcenter.bintray.com/org/sonatype/oss/oss-parent/3/oss-parent-3.pom (4 KB at 40.4 KB/sec)
[INFO] Downloading: https://jcenter.bintray.com/net/java/dev/javacc/javacc/5.0/javacc-5.0.pom
[INFO] Downloaded: https://jcenter.bintray.com/net/java/dev/javacc/javacc/5.0/javacc-5.0.pom (3 KB at 34.2 KB/sec)
[INFO] Downloading: https://jcenter.bintray.com/net/sourceforge/saxon/saxon/9.1.0.8/saxon-9.1.0.8.pom
[INFO] Downloaded: https://jcenter.bintray.com/net/sourceforge/saxon/saxon/9.1.0.8/saxon-9.1.0.8.pom (6 KB at 63.0 KB/sec)
[INFO] Downloading: https://jcenter.bintray.com/org/apache/commons/commons-lang3/3.4/commons-lang3-3.4.pom
[INFO] Downloaded: https://jcenter.bintray.com/org/apache/commons/commons-lang3/3.4/commons-lang3-3.4.pom (22 KB at 223.3 KB/sec)
[INFO] Downloading: https://jcenter.bintray.com/org/apache/commons/commons-parent/37/commons-parent-37.pom
[INFO] Downloaded: https://jcenter.bintray.com/org/apache/commons/commons-parent/37/commons-parent-37.pom (62 KB at 544.8 KB/sec)
[INFO] Downloading: https://jcenter.bintray.com/org/ow2/asm/asm/5.0.4/asm-5.0.4.pom
....
```

Travis is downloading the dependencies of the  static-code-analysis tool and it looks like it is trying to build it...

Maybe I will need some help with this issue.

**Comment by svilenvul** [comment]
@cweitkamp, and what about a local build, do you have the same results ? I have run the build on two different machines and no RequireBundle errors are reported.

@kaikreuzer do you have an idea what might cause the difference in the reports ?

**Comment by kaikreuzer** [comment]
No clue, sorry. There is definitely only one 0.1.0 release, so all builds should use the very same.

**Comment by cweitkamp** [comment]
@svilenvul As I said. My local build failed. That's the reason why I opend this issue.

I have deleted my local static-code-analysis-0.1.0.jar now. Run the build again and it looks like this:
```
....
Downloading: https://jcenter.bintray.com/org/openhab/tools/static-code-analysis/0.1.0/static-code-analysis-0.1.0.pom
Downloaded: https://jcenter.bintray.com/org/openhab/tools/static-code-analysis/0.1.0/static-code-analysis-0.1.0.pom (9 KB at 24.8 KB/sec)
Downloading: https://jcenter.bintray.com/org/openhab/tools/static-code-analysis/0.1.0/static-code-analysis-0.1.0.jar
Downloaded: https://jcenter.bintray.com/org/openhab/tools/static-code-analysis/0.1.0/static-code-analysis-0.1.0.jar (99 KB at 449.1 KB/sec)
[INFO] Computing target platform for MavenProject: org.eclipse.smarthome.archetype:org.openhab.binding.avmfritz.test:2.2.0-SNAPSHOT @ /home/christoph/workspace_4.6/openhab2-addons/addons/binding/org.openhab.binding.avmfritz.test/pom.xml
[INFO] Fetching p2.index from https://openhab.jfrog.io/openhab/eclipse-smarthome-stable/ (172B)
[INFO] Fetching p2.index from https://openhab.jfrog.io/openhab/eclipse-smarthome-stable/ (172B)
[INFO] Adding repository https://openhab.jfrog.io/openhab/eclipse-smarthome-stable

....
....
[INFO] 
[INFO] --- static-code-analysis:0.1.0:checkstyle (default) @ org.openhab.binding.avmfritz.test ---
[INFO] Adding dependency to checkstyle:7.7
[INFO] There is 1 error reported by Checkstyle 7.7 with jar:file:/XXX/.m2/repository/org/openhab/tools/static-code-analysis/0.1.0/static-code-analysis-0.1.0.jar!/rulesets/checkstyle/rules.xml ruleset.
[INFO] 
[INFO] --- static-code-analysis:0.1.0:pmd (default) @ org.openhab.binding.avmfritz.test ---
[INFO] 
[INFO] --- static-code-analysis:0.1.0:findbugs (default) @ org.openhab.binding.avmfritz.test ---
[INFO] Adding dependency to spotbugs:3.1.0-RC3
[INFO] Adding dependency to bug-pattern:1.2.4
[INFO] Fork Value is false
     [java] JVM args ignored when same JVM is used.
[INFO] Done FindBugs Analysis....
[INFO] 
[INFO] --- static-code-analysis:0.1.0:report (default) @ org.openhab.binding.avmfritz.test ---
[INFO] Individual report appended to summary report.

....
```
Could you try to build on your local machine with `mvn -U clean install` to force complete dependencies to be updated?

**Comment by svilenvul** [comment]
I think I know what caused the issue, it should be the path separator in the suppressions file ..., I am running the build on Windows.

PR will follow soon.

**Comment by cweitkamp** [comment]
Good catch. I am very glad you found it. Keep an going with your great work.

**Comment by svilenvul** [comment]
Thanks. Tested and confirmed. Sorry for the headaches.

**Comment by cweitkamp** [comment]
Thank you too. I think I have to wait for a new release of this tool to keep on going with my work.

**Comment by svilenvul** [comment]
A new release is expected soon.

**Comment by kaikreuzer** [comment]
Is this a request to me? I can do one this afternoon if you think that the current snapshot is stable enough.

**Comment by svilenvul** [comment]
Yes and no.

I hoped that the next version would be stable and feature rich enough to be included in the ESH build.
If you think that is possible, I wish to take more time and test it carefully.

**Comment by kaikreuzer** [comment]
Before we integrate it in ESH, I will have to create a CQ and get the use approved. I can start that process right now, it might take around a week. So if the current version is not yet good enough for ESH, it should be no issue - we can do a further release next week and you can use the time for further tests.
Let me know if I should do a release today and whether you want to merge anything first.

**Comment by htreu** [comment]
I just saw this discussion here _after_ creating another PR for the Require-Bundle issue: #134 
@svilenvul please have a look if this is okay since it does not disable the check but extends it for test fragments.

**Comment by svilenvul** [comment]
> Let me know if I should do a release today and whether you want to merge anything first.

OK, you can do it. Nothing else urgent is waiting for a merge for now.

**Comment by kaikreuzer** [comment]
Ok, will do it now, stay tuned :-)

**Comment by kaikreuzer** [comment]
Done: https://github.com/openhab/static-code-analysis/releases/tag/0.2.0

**Comment by kaikreuzer** [comment]
FTR: https://github.com/openhab/openhab-core/pull/180

**Comment by svilenvul** [comment]
Thanks !
