### ISSUE TITLE
XML validation check 

### ISSUE THREAD

**Issue by svilenvul** [openhab/static-code-analysis#136]
Currently we have a check that validates thing types, channel types and configurations against the xsd schemas and **logs an error if there is a violation.**

This check finds a problem in the following code: 
```
....
 <properties>
        	<property name="vendor">Philips</property>
        </properties>
        <representation-property>serialNumber</representation-property>
        
        <config-description>
            <parameter name="ipAddress" type="text">
...
```

The error message is: 
```
[ERROR] ERROR found by checkstyle: C:\prj\openHAB\EclipseIDE\git\smarthome\extensions\binding\org.eclipse.smarthome.binding.hue\ESH-INF\thing\bridge.xml:15 Invalid content was foun
d starting with element representation-property. One of {config-description, config-description-ref} is expected.
```

Eclipse as well marks the xml as invalid. 
![xml-validation](https://user-images.githubusercontent.com/7120104/29164101-1b810e40-7dc7-11e7-9bf5-690f44a30470.PNG)

How should we proceed in this case ?
- ignore the file ;
- update the XSD schema ;
- reduce the priority of the check;
- consider it as really an error and change the file;
- some other option, maybe ..

@kaikreuzer, please take a look.

**Comment by kaikreuzer** [comment]
This is due to https://github.com/eclipse/smarthome/issues/3963 - I am still struggling with my access rights to push the updated xsd :-/

**Comment by svilenvul** [comment]
Thanks, closing the issue.
