### ISSUE TITLE
Replace HeaderCheck with RegexpHeaderCheck

### ISSUE THREAD

**Issue by svilenvul** [openhab/static-code-analysis#141]
Migrated from https://github.com/openhab/static-code-analysis/pull/130#discussion_r131689883.

>  martinvw 7 days ago Member

>Can't we make the end year dynamic? Maybe by string replacing it ${current_year} => some java code

> svilenvul 2 minutes ago Member

> I guess we should move to RegexpHeaderCheck.

[RegexpHeaderCheck](http://api.dpml.net/checkstyle/3.5/com/puppycrawl/tools/checkstyle/checks/RegexpHeaderCheck.html)

**Comment by martinvw** [comment]
Sounds great!
