### ISSUE TITLE
Reduce memory allocation for findbugs

### ISSUE THREAD

**Issue by kaikreuzer** [openhab/static-code-analysis#15]
I am currently trying to run the checks within the [openHAB PR builder](https://openhab.ci.cloudbees.com/job/PR-openHAB2-Addons/).

This has only 1GB of total memory available and the Maven build exists with error 137, which seems to be due to a lack of available native memory.
I am therefore looking into reducing the memory consumption of the build.

What I have noticed is that the FindBugs plugins spawns a separate Java process and uses `-Xmx=512m` as a JVM parameter. I assume that this actually leads to the issue and wonder, if there is a way to reduce this to 256m (which I would hope should be enough for Findbugs to do its job).

**Comment by kaikreuzer** [comment]
Alternatively (probably even better), if there is a way to configure the findbugs plugin in a way that it does not start a separate JVM, it should help even more.

**Comment by svilenvul** [comment]
Findbugs Maven Plugin has a terrible documentation, [this ](http://maven-plugins.sourceforge.net/maven-findbugs-plugin/properties.html)is what I have found so far:

>maven.findbugs.jvmargs - It specifies any arguments that should be passed to the Java virtual machine used to run FindBugs. You may need to use this attribute to specify flags to increase the amount of memory the JVM may use if you are analyzing a very large program.

**Comment by svilenvul** [comment]
I am not sure what this parameter does : http://gleclaire.github.io/findbugs-maven-plugin/findbugs-mojo.html#fork, it may be also related.

**Comment by kaikreuzer** [comment]
At least it sounds like it.

**Comment by svilenvul** [comment]
These properties can be added to https://github.com/openhab/static-code-analysis/blob/master/src/main/resources/configuration/findbugs.properties.

**Comment by kaikreuzer** [comment]
Works well :-)

**Comment by svilenvul** [comment]
https://github.com/openhab/openhab2-addons/pull/2042#issuecomment-286741482

**Comment by kaikreuzer** [comment]
I would not say that it needs to be reopened - the memory consumption IS less because there isn't a second JVM anymore, so the fix fulfills its purpose. My comment was only about the fact that this alone does not seem to solve all issues on Jenkins...

**Comment by kaikreuzer** [comment]
Btw (sorry, maybe slightly off-topic): Did you already consider switching to https://github.com/spotbugs/spotbugs?

**Comment by svilenvul** [comment]
Looking at the [findbugs documentation](http://findbugs.sourceforge.net/manual/running.html#commandLineOptions) there is also another way to reduce the memory usage:

>-effort:min

>    This option disables analyses that increase precision but also increase memory consumption. You may want to try this option if you find that FindBugs runs out of memory, or takes an unusually long time to complete its analysis. 

I will create a PR for this as well.
