### ISSUE TITLE
Building GitHub Pull Requests

### ISSUE THREAD

**Issue by svilenvul** [openhab/static-code-analysis#161]
It will be great if we build the pull requests to the repository using Travis.

It should be relatively easy to setup this.

@kaikreuzer, do we have an account that is used across the different openHAB repositories and could we use it ? Or should we create a new one ?

**Comment by kaikreuzer** [comment]
Sure, just add a .travis.yml file and I'll make sure that Travis receives the web hooks from Github!

**Comment by svilenvul** [comment]
Thanks, I will add it.
