### ISSUE TITLE
Problems with repeated download of about.html file

### ISSUE THREAD

**Issue by doandzhi** [openhab/static-code-analysis#169]
I faced an error in the maven build with the following message log : 

`[ERROR] An exception was thrown, while trying to read the about.html url: https://raw.githubusercontent.com/openhab/openhab2-addons/master/src/etc/about.html. No checks for the about.html file will be done. Server returned HTTP response code: 503 for URL: https://raw.githubusercontent.com/openhab/openhab2-addons/master/src/etc/about.html`

I suppose that it has a lot in common with [this](https://github.com/openhab/static-code-analysis/issues/164) issue since the about.html file is downloaded a couple of times and in some bundles this error is logged.

**Comment by svilenvul** [comment]
Thanks for reporting it.

I guess we will go with the same approach - download the file only once.
