### ISSUE TITLE
PackageExportsNameCheck - doesn't report issues on different OS

### ISSUE THREAD

**Issue by svilenvul** [openhab/static-code-analysis#173]
See https://github.com/openhab/static-code-analysis/pull/172#issuecomment-325906017.

Has to be further investigated. More tests are needed with different paths (Linux, Windows).

It seems that no exceptions are thrown, the check is missing some issues.

**Comment by VelinYordanov** [comment]
Seems to be working on my machine(Windows 10).

**Comment by svilenvul** [comment]
It is ok on Linux too, so I think we can close it
