### ISSUE TITLE
Tool causes Maven Warnings

### ISSUE THREAD

**Issue by kaikreuzer** [openhab/static-code-analysis#18]
When this tool is activated in a build, there are many warnings like
```
[WARNING] Unable to locate Source XRef to link to - DISABLED
```
in the Maven build log.

It seems that [PMD requires some specific reporting plugin](http://stackoverflow.com/questions/12038238/unable-to-locate-source-xref-to-link-to) - could that be made part of the static analysis tool?

**Comment by svilenvul** [comment]
Thanks, I will take a look.

**Comment by svilenvul** [comment]
From what I have read so far, maven-jxr-plugin produces a cross-reference of the project's sources that can be used from PMD and Checkstyle to provide links to the exact place(line) in the source files.

My question is do you think this feature will be helpful, or you are just would like to remove the warnings from the build (this can be accomplished by simply adding a few lines to the plugins configuration) ?

**Comment by kaikreuzer** [comment]
Not sure if we would get the cross-references to work, especially as the main purpose of the tool is to run pre-checks on PRs. So probably it is enough to suppress the warning.
