### ISSUE TITLE
Use standard Mojo logging mechanism

### ISSUE THREAD

**Issue by maggu2810** [openhab/static-code-analysis#180]
As a plugin we should not pollute the classpath with dependencies.
We should also use the standard Mojo logging mechanism.

So, WDYT about dropping the dependency to slf4j?

Related to: https://github.com/eclipse/smarthome/issues/4202

**Comment by svilenvul** [comment]
I am OK with that.

Actually only the report mojo could replace the slf4j with the Mojo logging mechanism.

Most of the time, slf4j is used in the checkstyle checks. In these cases slf4j could be replaced with `org.apache.commons.logging`. Checkstyle already has a dependency to it, so no new dependencies will be required.
