### ISSUE TITLE
Build failure when started from directory different than root

### ISSUE THREAD

**Issue by svilenvul** [openhab/static-code-analysis#184]
When building a separate module from a multi-module build and using a custom ruleset.xml or suppression.xml the build fails with the following error:

```
[ERROR] Failed to execute goal org.openhab.tools:static-code-analysis:0.3.0:checkstyle (default) on project org.eclipse.smarthome.binding.sonos: Unable to execute mojo: An error has occurred in Checkstyle report generation. Failed during checkstyle execution: Unable to find suppressions file at location: D:\dev\openhab2\git\smarthome\extensions\binding\org.eclipse.smarthome.binding.sonos\tools\static-code-analysis\checkstyle\suppressions.xml: Could not find resource 'D:\dev\openhab2\git\smarthome\extensions\binding\org.eclipse.smarthome.binding.sonos\tools\static-code-analysis\checkstyle\suppressions.xml'.
```

The reason for that is that the mojo tries to resolve the path relative to the `${session.executionRootDirectory}` - https://github.com/openhab/static-code-analysis/blob/master/src/main/java/org/openhab/tools/analysis/tools/AbstractChecker.java#L123.

See https://github.com/eclipse/smarthome/issues/4230

**Comment by svilenvul** [comment]
Maybe the [documentation about the plugin configuration](https://github.com/openhab/static-code-analysis/blob/master/docs/maven-plugin.md#customization) could be updated with the changes in https://github.com/eclipse/smarthome/pull/4240/files.

**Comment by dstivanov** [comment]
I would suggest that we can try to check whether the issue is still reproducible with the current SAT version and then decide how to proceed.

**Comment by dstivanov** [comment]
After a discussion with @VelinYordanov @tanyatanyatanya and @lpapazow it seems that this issue is no longer reproducible and will be closed.
