### ISSUE TITLE
(non-Javadoc) 

### ISSUE THREAD

**Issue by martinvw** [openhab/static-code-analysis#196]
@kaikreuzer openhab2-addons has 18 `(non-Javadoc)` docblock like things, for example this one and the following one:

```
    /*
     * (non-Javadoc)
     *
     * @see java.lang.Object#toString()
     */
```

Should this be removed and maybe added as a check as well

See also https://stackoverflow.com/questions/4597329/does-non-javadoc-have-a-well-understood-meaning

**Comment by martinvw** [comment]
Copied from https://github.com/openhab/openhab2-addons/pull/2716#discussion_r139452720

**Comment by kaikreuzer** [comment]
Imho they should be removed.

**Comment by martinvw** [comment]
As a one time action or as a check or both?

**Comment by kaikreuzer** [comment]
at least one time. not sure if it is worth a check, up to you...

**Comment by martinvw** [comment]
I think it does only have a low prio, I created a PR to fix the existing ones

**Comment by svilenvul** [comment]
@martinvw, what do you think about a check in the future ? Or we should consider one time action enough for this case ?

**Comment by martinvw** [comment]
The stackoverflow suggests that it was because of bug in eclipse long time ago, so I think its just a relic of the past and a check might not be needed. And if we add it it has very low prio

**Comment by svilenvul** [comment]
OK, I am closing it then.
