### ISSUE TITLE
OSGi - Check for Private References

### ISSUE THREAD

**Issue by svilenvul** [openhab/static-code-analysis#210]
Reading the discussion in https://github.com/eclipse/smarthome/issues/4330, I thinks this a good candidate for a static code analysis.

As you can see in the shared link - http://enroute.osgi.org/tutorial_wrap/270-private-references.html, a class that is in exported package should not use a class from private package in its public API, because the API will be unusable.

The check could notify the developer to export the private package being used.

**Comment by svilenvul** [comment]
Just to make it more clear - protected/public methods in classes that are exported should not use types  that are internal (all that are defined in the bundle, but are not exported) in the method definition.

**Comment by svilenvul** [comment]
@kaikreuzer, wdyt ?

**Comment by kaikreuzer** [comment]
Makes a lot of sense to me - can even be made error level. 👍

**Comment by VelinYordanov** [comment]
@kaikreuzer Currently the check finds more than 300 errors in smarthome and openhab so I think warning severity might be better until we fix all problems.
