### ISSUE TITLE
[Logging] add more FindBugs patterns from findbugs-slf4j

### ISSUE THREAD

**Issue by svilenvul** [openhab/static-code-analysis#213]
The tool is using https://github.com/KengoTODA/findbugs-slf4j for verifying logging messages, but not all patterns that this plugin offers are in use.

I have noticed two good candidates:
- [this pattern alerts if count of placeholder does not match to count of parameter](https://github.com/KengoTODA/findbugs-slf4j#slf4j_place_holder_mismatch)
- [this pattern reports that illegal class is passed to LoggerFactory.getLogger(Class)](https://github.com/KengoTODA/findbugs-slf4j#slf4j_illegal_passed_class)

In order to add them to the tool, the detectors that recognize these patterns should be added to the tool configuration.

I think the severity is currently error for FindBugs checks, so the code base might have to be cleaned up.

**Comment by svilenvul** [comment]
I have tested the second detector on ESH, but I have found some issues with it : https://github.com/KengoTODA/findbugs-slf4j/issues/61

**Comment by martinvw** [comment]
As @magu2810 pointed out the suggestion of the detector seems correct since the given class does not use a logger from his own or any outer class but a parent class instead. Lets introduce this check 🙂

**Comment by svilenvul** [comment]
So I must have misunderstood him. Should I close the issue then ?

And what do you think about the second suggestion - should using an interface instead of the implementing class be reported as well as error ?

**Comment by martinvw** [comment]
I do indeed also agree on this one, because if you configure one of the default logging patterns, the results is that the logging shows that the problem originates from that interface instead of the actual implementation, it becomes especially confusing if you would enable the line endings because then it really stops making sense.

So indeed a logger should refer to the class it is in or one of the outer classes.

**Comment by maggu2810** [comment]
> So I must have misunderstood him.

@svilenvul It seems so Sorry that I haven't been clear enough.
@martinvw Thanks for explaining my comment. :wink:
