### ISSUE TITLE
Documentation style Check needed? 

### ISSUE THREAD

**Issue by kssimova** [openhab/static-code-analysis#215]
Based on comments I have read, I did a research and I did not find checks that cover the cases I presented below. I think that it is a good idea to discuss them . 

- There should be no dash between the parameter name and the description in a Javadoc comment of a method or constructor. For example: https://github.com/eclipse/smarthome/pull/1597#issuecomment-225444240

```java
    /** 
    * @param watchService - the watch service, providing the watch events for the watched directory
    * @param toWatch - the directory being watched by the watch service
    * @param registredWatchKeys - a mapping between the registered directories and their {@link
    WatchKey registration keys}.
    * @return the concrete queue reader
    */
    protected abstract AbstractWatchQueueReader buildWatchQueueReade(WatchService watchService,
    Path toWatch, Map<WatchKey, Path> registredWatchKeys);
```

- The parameter description in a Javadoc comment of a method or constructor should not start on a new line. For example: https://github.com/eclipse/smarthome/pull/1597#issuecomment-225951396

```java
    /**
    * @param event 
    * 		                the watch event to perform
    * @param kind 
    *		                the event’s kind
    * @param name 
    *		                the path of the event
    */
    protected abstract void processWatchEvent(WatchEvent<?> event, WatchEvent.Kind<?> kind, Path 
    path);
```

- There should be no empty lines between tags. For example: https://github.com/eclipse/smarthome/pull/1597#issuecomment-225951396

```java
    /**
    * @param watchService the watch service
    * 	
    * @param watchedDir the base directory, watched by the watch service
    * 
    * @param registeredKeys a mapping between the {@link WatchKey}s and their corresponding * 
    directories, registered in the watch service. 
    */
    public AbstractWatchQueueReader(WatchService watchService, Path watchedDir, Map<WatchKey, 
    Path> registeredKeys){
   	... 
    }
```
@kaikreuzer , @martinvw what do you think?

**Comment by kaikreuzer** [comment]
Sorry again for not having responded - I like those checks! 👍
