### ISSUE TITLE
Javadoc for methods/variables of exported classes

### ISSUE THREAD

**Issue by svilenvul** [openhab/static-code-analysis#219]
Currently we have the [JavadocFilterCheck](https://github.com/openhab/static-code-analysis/blob/master/src/main/java/org/openhab/tools/analysis/checkstyle/JavadocFilterCheck.java) which checks **classes** for missing javadoc, but we can add further checks for **methods and variables**.

A good candidate for that may be:
https://github.com/Adobe-Consulting-Services/checkstyle-osgi-checks

>This is a series of Checkstyle checks specific to working in an OSGi environment.
ExportedJavadocMethod
Same as JavadocMethod, but allows missing JavaDoc on non-exported classes.
ExportedJavadocType
Same as JavadocType, but allows missing JavaDoc on non-exported classes.
ExportedJavadocVariable
Same as JavadocVariable, but allows missing JavaDoc on non-exported classes.

It is available on [mvnrepository](https://mvnrepository.com/artifact/com.adobe.acs/checkstyle-osgi-checks) as well.

**Comment by svilenvul** [comment]
Actually it is not in MVNrepository :-(, it is in https://repo.adobe.com/nexus/content/repositories/public/.

**Comment by svilenvul** [comment]
This repository is dead, no new commits in the last few years. The version of the Checkstyle API that is being used is outdated.

We should implement the checks by our own.

**Comment by VelinYordanov** [comment]
I'll start work on that.
