### ISSUE TITLE
Check for slf4j usage

### ISSUE THREAD

**Issue by svilenvul** [openhab/static-code-analysis#220]
We have several checks for verifying correct usage of slf4j, but we don't have a check if any other logging framework/implementation is used instead (logback, commons-logging, log4j, etc.).

In the [ESH guidelines](https://www.eclipse.org/smarthome/documentation/development/guidelines.html#c-language-levels-and-libraries) it is mentioned that slf4j should be used always for logging.

**Comment by lpapazow** [comment]
I will start working on such check

**Comment by wborn** [comment]
The check was merged in #291.
