### ISSUE TITLE
Release new version of the tool

### ISSUE THREAD

**Issue by svilenvul** [openhab/static-code-analysis#231]
@kaikreuzer,

I think we can release new version of the tool before Christmas :).

Few PRs are opened to keep the builds green after the new release.

- https://github.com/eclipse/smarthome/pull/4749
- https://github.com/openhab/openhab2-addons/pull/2810
- https://github.com/openhab/openhab-core/pull/262

My local builds did not show any other errors in smarthome, openhab-distro, openhab2-addons, openhab-core repos. I hope I have not missed something.

Please take a look at it when you have time.

**Comment by kaikreuzer** [comment]
Ok, thanks! I'll take care of this next week. On Monday is openHAB 2.2 release, so I won't touch anything on the openHAB side before that ;-)

**Comment by kaikreuzer** [comment]
Hey @svilenvul, sorry for being late! I've reserved some time today to deal with a new release.
Is the code base in a good state for that or would you first want to merge any pending PRs?

**Comment by svilenvul** [comment]
@kaikreuzer, sorry for the delay from my side as well.

The last thing that we can include in the release is https://github.com/openhab/static-code-analysis/pull/239, I suggest to leave the other PRs for the next one. :)

I think the code base is in a good state, so feel free to release the new version, when you find time for that.

**Comment by kaikreuzer** [comment]
Done: https://github.com/openhab/static-code-analysis/releases/tag/0.4.0

Master is now 0.5.0-SNAPSHOT.

**Comment by kaikreuzer** [comment]
@svilenvul Could you be so kind and check/update the PRs for the different repos that use the SAT? Thanks!

**Comment by svilenvul** [comment]
Yes, I will work today on it.

**Comment by kaikreuzer** [comment]
You have to choose the correct pom in the upper right corner:

<img width="593" alt="screen shot 2018-01-19 at 11 11 01" src="https://user-images.githubusercontent.com/3244965/35145835-8674e05c-fd09-11e7-9d07-13bab310c165.png">

So the release was successful. If it isn't usable, I can do a 0.4.1 with your updates, no problem.
Is [this commit](https://github.com/openhab/static-code-analysis/commit/da1a8b52e118a02559f5063eb6a70092388667cc) all it needs?

**Comment by svilenvul** [comment]
@kaikreuzer, the branch https://github.com/openhab/static-code-analysis/tree/release-0.4.1 is ready for a release.

**Comment by kaikreuzer** [comment]
Thanks, will do the release later today!

**Comment by kaikreuzer** [comment]
Done: https://github.com/openhab/static-code-analysis/releases/tag/0.4.1

**Comment by kaikreuzer** [comment]
FTR: I still do not know why it doesn't turn up on JCenter, but I took the chance to apply for inclusion in Maven Central - I hope I am able to push it there soon!

**Comment by kaikreuzer** [comment]
Success! http://repo1.maven.org/maven2/org/openhab/tools/sat/sat-plugin/0.4.1/

**Comment by kaikreuzer** [comment]
So I would claim that we can even remove the JCenter repo from the ESH pom when updating to that SAT version.

**Comment by svilenvul** [comment]
Thanks a lot :)
