### ISSUE TITLE
Improve build times using the tool

### ISSUE THREAD

**Issue by svilenvul** [openhab/static-code-analysis#232]
Currently the build times for openHAB and Eclipse SmartHome are very high (both for local build and CI PR builds) is and as the project grow this becomes even worse.

As we have already discussed in https://github.com/eclipse/smarthome/pull/3995#issuecomment-322392976 FindBugs(SpotBugs) analysis are especially slow.

What we have discussed with @dstivanov is, if we can make more intelligent use of the tool in the build system. We have gathered the following ideas:
- for nightly builds : use the current approach to execute all checks on all bundles;
- for PR CI builds :  search for an option to execute all checks only on bundles that are changed;
- for local builds : maybe do not execute the checks at all, or if possible execute only on changed bundles;

Most of the checks (except few FindBugs and a few exceptions) are isolated to a single bundle, so this should not be a compromise with the code quality aspect.

We wanted to start this discussion and together gather ideas, so please share your opinions on this topic.

**Comment by svilenvul** [comment]
One way to accomplish the requirements above could be:

- write script that uses `git diff master` to see which files are being changed and extract the Maven artifact IDs of the changed bundles;
- add a new property to the static code analysis tool which accepts a list of Maven artifact IDs. In case the bundle is not in the list, the execution can be skipped.

@dstivanov, please ping me to discuss the details

**Comment by svilenvul** [comment]
Checkstyle also has a [cache support](http://checkstyle.sourceforge.net/config_reporting.html#Caching_Support). Maybe additional configuration is needed in the ruleset as well - http://checkstyle.sourceforge.net/config.html

**Comment by svilenvul** [comment]
Ideas can be gathered from SonarQube as well, maybe a good starting point is their issue tracker - [Support incremental code quality analysis](https://jira.sonarsource.com/browse/SONAR-2815?jql=text%20~%20%22incremental%22).

**Comment by svilenvul** [comment]
For SpotBugs, incremental build support is in the 4.0.0 Roadmap - https://github.com/spotbugs/spotbugs/wiki/Roadmap. Unfortunately I can not see any progress on this feature, as there is no opened issue in GitHub.

The closest that I can find is https://github.com/spotbugs/spotbugs/issues/249

**Comment by martinvw** [comment]
> I see that PMD supports Incremental Analysis since version 6.0.0 -https://pmd.github.io/pmd-6.2.0/pmd_userdocs_getting_started.html#incremental-analysis.
> 
> Interesting is also that in the 6.2.0 release notes, they it is not useful with CI jobs - https://pmd.github.io/pmd-6.2.0/pmd_release_notes.html#disable-incremental-analysis.

I still think this could be valuable for local builds 👍
