### ISSUE TITLE
Avoid Throwing Null Pointer Exception

### ISSUE THREAD

**Issue by cweitkamp** [openhab/static-code-analysis#249]
I'm not sure if it's related to the `sca` tool or the `sat-plugin`.

The rule
```
sat-plugin/src/main/resources/rulesets/pmd/rules.xml:  <rule ref="rulesets/java/strictexception.xml/AvoidThrowingNullPointerException">
```
checks for `throw NullPointerException` (see below). What about using the [Objects.requireNonNull()](https://docs.oracle.com/javase/7/docs/api/java/util/Objects.html#requireNonNull(T)) methods?

```
[ERROR] Code Analysis Tool has found: 
 3 error(s)! 
 1 warning(s) 
 12 info(s)
[ERROR] org.eclipse.smarthome.core.audio.internal.AudioManagerImpl.java:[99]
Avoid throwing null pointer exceptions.
[ERROR] org.eclipse.smarthome.core.audio.internal.AudioManagerImpl.java:[146]
Avoid throwing null pointer exceptions.
[ERROR] org.eclipse.smarthome.core.audio.internal.AudioManagerImpl.java:[172]
Avoid throwing null pointer exceptions.
```

**Comment by martinvw** [comment]
What do you mean, I personally think that using `Objects.requireNonNull()` is okay, it just makes sure the code fails early and predictable when undesired `null`'s are passed.

Although in our case in ESH / openHAB we have more powerful tools with the null-related annotations.

**Comment by cweitkamp** [comment]
In general I wanted to discuss what you think about those util methods. The day I filed this issue I thought there is no big difference between throwing a NPE and using this helper to check a parameter and throw the NPE if necessary. I completely forget about the different use cases. After some sleep I think I can close this issue again.
