### ISSUE TITLE
Check reports files that are automatically generated

### ISSUE THREAD

**Issue by kssimova** [openhab/static-code-analysis#255]
Currently, *NewLineAtEndOfFileCheck* reports **.xml** files, which are located in the **OSGI-INF** folder and are included in *.gitignore* file. The check is from *com.puppycrawl.tools.checkstyle.checks*, so changing it directly is not an option. As these files are automatically generated, what should we do to not report them anymore? Perhaps we should find a way to ignore all **OSGI-INF** folders for the check? 
@kaikreuzer @martinvw wdyt?

**Comment by tanyatanyatanya** [comment]
@kssimova  OnlyTabIdentationInXmlFilesCheck also reports .xml files located in the OSGI-INF folders.

**Comment by lpapazow** [comment]
I will create a custom checkstyle [filter](http://checkstyle.sourceforge.net/writingfilters.html) that checks if a file is ignored by git (a .gitignore file is present in the same directory) and skips the file if it is .gitignored.

The filter should be generic and suppress reports for all checks.
