### ISSUE TITLE
KarafFeatureCheck: openHAB dependency?

### ISSUE THREAD

**Issue by maggu2810** [openhab/static-code-analysis#264]
Is there some hardcoded openHAB stuff in the SAT?

It seems `Chiranjeevi B` gets this message:

```
[WARNING] KarafFeatureCheck will be skipped. Could not find file features/openhab-addons/src/main/feature/feature.xml
```

Have a look at the report here: https://www.eclipse.org/forums/index.php?t=msg&th=1091663&goto=1782784&#msg_1782784

**Comment by svilenvul** [comment]
The check was initially created specifically for openHAB.

I do not know if it can be useful for Eclipse SmartHome currently.

If no, it should not run in this build.

**Comment by maggu2810** [comment]
Can you point me to the documentation (or perhaps source code) to understand what this check is used for?

**Comment by svilenvul** [comment]
`Checks if a bundle is added in a Karaf feature.xml file`- https://github.com/openhab/static-code-analysis/blob/2ce6b8c3cf1e4173f1e7047bc291cb4c643a01ed/custom-checks/checkstyle/src/main/java/org/openhab/tools/analysis/checkstyle/KarafFeatureCheck.java

The idea was that without adding the bundle in the feature file, it won't be installable through the Karaf console.

**Comment by maggu2810** [comment]
Hm, for ESH there are at least three feature files.
```
features/karaf/esh-core/src/main/feature/feature.xml
features/karaf/esh-ext/src/main/feature/feature.xml
features/karaf/esh-tp/src/main/feature/feature.xml
```

**Comment by svilenvul** [comment]
We can adapt the check to verify if a bundle is included in any of the feature files in ESH.

WDYT about this option ?

**Comment by maggu2810** [comment]
Would it make sense to make the list of feature files to respect configurable?

**Comment by svilenvul** [comment]
Yes, it fully makes sense.

**Comment by maggu2810** [comment]
Are there any plans to release a new version that contains a fix?
It would be great if we could get rid of the warning that is logged for every bundle while building ESH.
