### ISSUE TITLE
DeclarativeServicesDependencyInjectionCheck warns about uses of ServiceTracker that are probably unavoidable.

### ISSUE THREAD

**Issue by lpapazow** [openhab/static-code-analysis#265]
The `DeclarativeServicesDependencyInjectionCheck`  triggers **"Avoid using ServiceTracker/ServiceTrackerCusttomizer for dependency injection, consider using Declarative Services"** warnings in the following `abstract` classes:

- org.eclipse.smarthome.core.thing.binding.BaseThingHandler
- org.eclipse.smarthome.core.thing.binding.BaseThingHandlerFactory
- org.eclipse.smarthome.automation.internal.commands.AbstractCommandProvider
- org.eclipse.smarthome.core.common.registry.AbstractRegistry
- org.eclipse.smarthome.core.transform.AbstractFileTransformationService

According to 112.8.1 in the [R6](https://osgi.org/download/r6/osgi.cmpn-6.0.0.pdf) spec,
`The Component Annotations are not inherited, they can only be used on a given class, annotations on its super class hierarchy or interfaces are not taken into account.`
Because of that, I don't think there is a way to use `DS` only in the abstract classes, but every concrete class needs to have its own `@Reference` annotation and I don't consider refactoring every concrete class to be an option.

I can only thing of 2 possible ways to get rid of these warnings: 

1. Keep the check unchanged and add suppressions for these particular classes.
2. Rework the check to not warn about ServiceTrackers in abstract classes.

Which of these two options seems more appropriate?
@kaikreuzer,  @htreu, @maggu2810

**Comment by htreu** [comment]
We should keep the warning as it is but suppress it for our "special" cases. No further classes using ServiceTrackers should be introduced and abstract classes are especially prone to use them.

fyi: For the `BaseThingHandler` we already plan to remove the ServiceTracker and pass the required services from the `BaseThingHandlerFactory`. But the other candidates are hard to refactor.

**Comment by maggu2810** [comment]
You are right, annotations are (normally) not inherited (but they can be using appropriate tooling).
I agree with @htreu, that the warning should be kept, but suppressed in some of our special use cases.
