### ISSUE TITLE
ConstantNameCheck final references issue

### ISSUE THREAD

**Issue by VelinYordanov** [openhab/static-code-analysis#267]
The [Java Coding Style Guide](https://web.archive.org/web/20120911192801/developers.sun.com/sunstudio/products/archive/whitepapers/java-style.pdf) states in paragraph 3.3 Field Naming

> Names of fields being used as constants should be all upper-case, with underscores separating words. The following are considered to be constants:
> 1. All `static final` primitive types (Remember that all interface fields are inherently static final).
> 2. All `static final` object reference types that are never followed by "." (dot).
> 3. All `static final` arrays that are never followed by "[" (dot).
> 
> Examples:
> `MIN_VALUE, MAX_BUFFER_SIZE, OPTIONS_FILE_NAME`

However the ConstantNameCheck currently displays a warning for all static final objects.
For example:
`public static final Logger logger = LoggerFactory.getLogger(MethodHandles.lookup().lookupClass());`

Following this convention, `logger` is a static final object reference as stated in point 2, but because it is followed by "." every time you use it, it can not be considered as a constant and thus should be lower case, however the check produces a warning with the following message : 
`Name 'logger' must match pattern '^[A-Z][A-Z0-9]*(_[A-Z0-9]+)*$'.`

In my opinion the check needs to be adjusted to the coding style guide.
@svilenvul @kaikreuzer @sjka WDYT

**Comment by martinvw** [comment]
I personally really think that `2)` is a mistake from Sun.

Because `2)` excludes String's because if you compare with a constant you should actually use `equals` on the constant and not vice versa.

And it would also mean that we might not be supposed to call methods (eg. `equals`) on `BigDecimal.ZERO` and others.

Note that loggers should NOT be static anyway in openHAB / ESH so the example is imho a non-issue for us.

**Comment by kaikreuzer** [comment]
I do not understand the issue yet, sorry. You say:

> the ConstantNameCheck currently displays a warning for all static final objects.
> For example:
> `public final Logger logger = LoggerFactory.getLogger(MethodHandles.lookup().lookupClass());`

But this example is NOT static, so why is there a warning?

**Comment by VelinYordanov** [comment]
Sorry, that's my mistake, it should be static. I edited the issue.

**Comment by kaikreuzer** [comment]
In that case, I would agree with the message: The logger should be called `LOGGER`.

**Comment by martinvw** [comment]
> Sorry, that's my mistake, it should be static in the example. I edited the issue.

But:

Martinvw:
> Note that loggers should NOT be static anyway in openHAB / ESH so the example is imho a non-issue for us.

@VelinYordanov what do you think of the examples I posted?

**Comment by VelinYordanov** [comment]
I agree with your points.

**Comment by svilenvul** [comment]
@VelinYordanov, if no changes to the check are required, can we close this issue ?
