### ISSUE TITLE
Typos in readme

### ISSUE THREAD

**Issue by maggu2810** [openhab/static-code-analysis#27]
Singular vs. plural: a user properties
https://github.com/MusalaSoft/static-code-analysis/blame/8ea229cdc77f1ba07e86aa2ec845ef03e2de4729/README.md#L174

**Comment by maggu2810** [comment]
Missing closing bracket:
https://github.com/MusalaSoft/static-code-analysis/blame/8ea229cdc77f1ba07e86aa2ec845ef03e2de4729/README.md#L203

**Comment by maggu2810** [comment]
Different path separators are used (normally you use `/` instead of `/`):
https://github.com/MusalaSoft/static-code-analysis/blame/8ea229cdc77f1ba07e86aa2ec845ef03e2de4729/README.md#L216

**Comment by kaikreuzer** [comment]
Could you directly create a PR with the fixes?

**Comment by maggu2810** [comment]
Created #28, but I don't know if it is a user property or if there are user properties -- so IMHO this should be fixes by someone who knows the correct documentation.

**Comment by svilenvul** [comment]
> but I don't know if it is a user property or if there are user properties

user properties is correct
