### ISSUE TITLE
Trailing whitespaces

### ISSUE THREAD

**Issue by maggu2810** [openhab/static-code-analysis#272]
WDYT about a test that complains about trailing whitespace?
An inclusion and exclusion list (regular expression for the path pattern) could make sense.

**Comment by svilenvul** [comment]
Examples can be found in the Checkstyle documentation - http://checkstyle.sourceforge.net/config_regexp.html#RegexpSingleline

**Comment by wborn** [comment]
The Spotless `check` goal will also detect these issues. They are easily fixed by the `apply` goal.

Shall we close this issue and PR (https://github.com/openhab/static-code-analysis/pull/300) for implementing it @openhab/sat-maintainers?

**Comment by kaikreuzer** [comment]
Sure.
