### ISSUE TITLE
minimal setup to get SAT working

### ISSUE THREAD

**Issue by maggu2810** [openhab/static-code-analysis#275]
I run into a problem with SAT and tried to create a simple demo project to reproduce the error.

But I failed to create a minimal setup for the SAT execution.

Can you have a look at [minimal-setup] please and tell my what is missing?

```text
[ERROR] Failed to execute goal org.openhab.tools.sat:sat-plugin:0.4.1:checkstyle (default) on project minimal-setup: Unable to execute mojo: Execution null of goal org.apache.maven.plugins:maven-checkstyle-plugin:2.17:checkstyle failed: Plugin org.apache.maven.plugins:maven-checkstyle-plugin:2.17 or one of its dependencies could not be resolved: Failed to collect dependencies at org.apache.maven.plugins:maven-checkstyle-plugin:jar:2.17 -> org.openhab.tools.sat.custom-checks:checkstyle:jar:0.4.1 -> org.eclipse.pde:org.eclipse.pde.core:jar:3.11.1 -> org.eclipse.jdt:org.eclipse.jdt.core:jar:3.13.0 -> org.eclipse.platform:org.eclipse.core.resources:jar:[3.12.0,4.0.0): No versions available for org.eclipse.platform:org.eclipse.core.resources:jar:[3.12.0,4.0.0) within specified range -> [Help 1]
```

[minimal-setup]: https://github.com/maggu2810/static-code-analysis-test/tree/master/minimal-setup

**Comment by svilenvul** [comment]
Sorry, I was not able to reproduce it in a clean workspace: 

[static-code-analysis-test.txt](https://github.com/openhab/static-code-analysis/files/1840525/static-code-analysis-test.txt)

**Comment by maggu2810** [comment]
Have you tried to use an empty local Maven repository?

```sh
$ mvn clean install -Dmaven.repo.local=/some/empty/directory
```

**Comment by svilenvul** [comment]
This should be empty, it is the first execution in the new workspace.

**Comment by maggu2810** [comment]
What do you associate with a new workplace?
The local Maven repository exists once per user. It's normally placed in ${M2_HOME}/repository = ${HOME}/.m2/repository

**Comment by svilenvul** [comment]
```
[SAT-Minimal-Setup-Test] $ /opt/maven3.5.3/apache-maven-3.5.3/bin/mvn -f minimal-setup/pom.xml -s /home/jenkins/workspace/SAT-Minimal-Setup-Test/settings.xml -Dmaven.repo.local=/home/jenkins/workspace/SAT-Minimal-Setup-Test/.repository clean verify
```

This was the first run in the `/home/jenkins/workspace/SAT-Minimal-Setup-Test` folder, so everything should be empty.

**Comment by maggu2810** [comment]
That is strange, cannot reproduce it myself anymore.
Sorry
