### ISSUE TITLE
add "skip" configuration option

### ISSUE THREAD

**Issue by maggu2810** [openhab/static-code-analysis#284]
The configuration of the mojo should support a "skip" parameter.
A skip parameter is supported by a lot of mojos.

This will e.g. allow to add the plugin configuration to the base pom in its default profile and just set the property in dependence of e.g. a special file etc.

Perhaps there should be multiple skip options to allow an easy to use and fine granulated control.

WRT to the current usage in ESH there could be one global skip option for the plugin that is controlled / set in respect of the "skipChecks" property. "skipChecks" could e.g. set "sat.skip" that will be used in the respective plugin configuration. If that skip is set no checks are executed.

IMHO not necessary at the moment as the plugin itself could execute the tests dependent of the presence of files itself:
Then there could be properties (if "skip" is not set), that defines the checks that are executed.
The presence of the `MANIFEST.MF` could e.g. control the value of "executeManifestMfChecks".
The presence of the `src/.../feature.xml` could e.g. control the value of "executeKarafFeatureChecks".

**Comment by maggu2810** [comment]
Example usage: https://github.com/eclipse/smarthome/compare/master...maggu2810:sat-skip?expand=1

**Comment by splatch** [comment]
I would apprecieate this option. Current build of Eclipse Smart Home and OpenHab takes quite long time (due to tycho) and skipping static code analysis which parses most, if not all, files is place where I look for biggest performance boost.
Currently getting developer feedback from custom ESH build takes simply too much time.

**Comment by splatch** [comment]
Yeah, I spotted it and use it. It saves a lot of time during build.

**Comment by svilenvul** [comment]
@VelinYordanov is working on this one.

**Comment by dstivanov** [comment]
As the PR is updated - the task is again ready for review.
