### ISSUE TITLE
Static Code Analysis Tool to strict on AuthorTagCheck

### ISSUE THREAD

**Issue by kgoderis** [openhab/static-code-analysis#288]
Currently the SCAT classifies AuthorTagCheck as priority 1 issues. Although this is with good intention, this is troublesome for .java files that are generated by a third party tool, for example when using 'xjc' to generate java classes from xsd files using JAXB annotations. Manually adding AuthorTags to generated files is troublesome as these files are often overwritten on the next execution of the third party tool.

**Comment by martinvw** [comment]
Good question.

In the case:

> Manually adding AuthorTags to generated files is troublesome as these files are often overwritten on the next execution of the third party tool.

I would vote for letting the generation happen in the the `target` directory, but I remember that me & @kaikreuzer had a distinct opinion about this in the past ;-)

**Comment by svilenvul** [comment]
Another option would be to generate the files in `src/gen/java` or `src-gen` folder that is not being checked by SCAT (at least Checkstyle).

This is being currently used in ESH. On top of that I see a filter - https://github.com/eclipse/smarthome/blob/68ce82a5d61b7576fec47aaf82cb5336bd8fd2cc/tools/static-code-analysis/checkstyle/suppressions.xml#L13.

As this is more a matter of project setup and configuration of the tool, I hope you don`t mind if I close the issue.

**Comment by kgoderis** [comment]
@svilenvul mhhh.. the files that are generated by the tool are modified afterwards to include the proper copyright heading. In this case, xjc is ran independently from the eclipse compilation process. I have no experience on how to set up the bundle in eclipse so that code is generated in src/gen/java
