### ISSUE TITLE
Release new version of the tool - 0.5.0

### ISSUE THREAD

**Issue by svilenvul** [openhab/static-code-analysis#293]
@kaikreuzer 

We have successfully tested the https://github.com/openhab/static-code-analysis/releases/tag/0.5.0-alpha version with the latest state of :
- openhab-core : https://github.com/openhab/openhab-core/commit/c02826f882aefc57f900f5ba54cc59c1e0fc9f32
- openhab2-addons : https://github.com/openhab/openhab2-addons/commit/0c8fef577669960cdf60b7667615089cd5d23cd6
- smarthome : https://github.com/eclipse/smarthome/commit/bb57a140d9e1979d3b4f055f8210dada73cd2f3a

Since the last release is from the end of January, it would be great if you can prepare a new one.

**Comment by kaikreuzer** [comment]
Will do!

**Comment by kaikreuzer** [comment]
Done! https://github.com/openhab/static-code-analysis/releases/tag/0.5.0
