### ISSUE TITLE
Content of default ruleset files

### ISSUE THREAD

**Issue by svilenvul** [openhab/static-code-analysis#31]
When we started the discussion for the tool, one of the requirements was the option to have different rule sets for different kinds of projects (bundle, binding, ui,...).

The tool contains a set of [default ruleset files](https://github.com/openhab/static-code-analysis/tree/master/src/main/resources/rulesets) that will be used when executing the Maven plugin without additional configuration. 

Optionally in another Maven profile we can configure the tool to use another set of .xml files as it is described [here](https://github.com/openhab/static-code-analysis#customization). So far so good.

In the openHAB addons build we are using currently only the **default rulesets**. What should these rulesets contain ? Options are :
- checks that apply only for binding;
- checks that **apply for bundles (this the case now);**
- some other set of checks.

This question is related to #25 - https://github.com/openhab/static-code-analysis/pull/25#issuecomment-288875725. 

*If we keep the current defaults, we should add another set of rules in the OH2 adddons repository only for bindings.* (where the check for README.MD can be included) and add another Maven profile. I am not sure if it is worth it, as only few checks are not applicable for both bindings and bundles... and we should maintain another set of .xml files.

@kaikreuzer, what do you think - should we change the default ruleset files to include checks only for bindings (and skip checking 'none-bindnigs' in OH2 for now) or we should start using separate profiles for bindings and for other type of projects?

**Comment by kaikreuzer** [comment]
Not sure if I fully understand the question. I thought we already have [two different profiles](https://github.com/openhab/openhab2-addons/blob/master/pom.xml#L313-L363) in place for openHAB - one for bundles in general and one that is activated only for bindings.

**Comment by svilenvul** [comment]
Yes, we have two profiles, but the first one applies only general settings (set the goals, it doesn't add the static-code-analysis to the build) and the second one applies the default ruleset files for all bundles.

Should we keep ruleset files for both bindings and bundles in the static-code-analysis repo or better add them to the OH2 repo and keep only a 'default' set of rules (as an example) in the static-code-analysis repo? 

ESH will definitely need a  separate set of ruleset files in the ESH repo, because some checks as HeaderCheck check will need different configuration.

**Comment by kaikreuzer** [comment]
> the first one applies only general settings (set the goals, it doesn't add the static-code-analysis to the build) and the second one applies the default ruleset files for all bundles.

Indeed, you are right. I somehow had in mind that we already had a specific profile that was activated for bindings...

> Should we keep ruleset files for both bindings and bundles in the static-code-analysis repo

I would say yes, as also for ESH we will require specific rules for bindings.

> ESH will definitely need a separate set of ruleset files in the ESH repo, because some checks as HeaderCheck check will need different configuration.

Yes, there will be some differences, but we also have differences wrt the general checks for bundles (e.g. different about.html, potentially difference license headers, etc.). So I would hope that it is possible to deactivate existing checks from the tool, where required and also to add additional checks. Is this realistic?

**Comment by svilenvul** [comment]
> Yes, there will be some differences, but we also have differences wrt the general checks for bundles (e.g. different about.html, potentially difference license headers, etc.).

This is exactly why I would prefer that each repo keeps its own set of ruleset files.

> So I would hope that it is possible to deactivate existing checks from the tool, where required and also to add additional checks. Is this realistic?

Deactivating may be possible, but I couldn't think of an easy way to overwrite configuration of a check.

**Comment by kaikreuzer** [comment]
> This is exactly why I would prefer that each repo keeps its own set of ruleset files.

I am probably not deep enough in your vocabulary - I would actually say that we do not need different "rule sets", but the very same rules, but with a different configuration, i.e. do the "license header check rule" with a different license header file as a configuration.

> Deactivating may be possible, but I couldn't think of an easy way to overwrite configuration of a check.

If the granularity level is on single checks (like the license header check, author tag check, etc.), then a deactivation possibility within the pom.xml of a single bundle would imho be fully ok.

**Comment by svilenvul** [comment]
I have found something that may help, the Checkstyle configuration file may have properties in the configuration file - https://maven.apache.org/plugins/maven-checkstyle-plugin/examples/custom-property-expansion.html

**Comment by svilenvul** [comment]
> The property element provides an optional default attribute which is used when a property in the value cannot be resolved. For example this configuration snippet from a central configuration file checks that methods have javadoc, but allows individual projects to override the severity by specifying their desired value in the command line property checkstyle.javadoc.severity: 

From: http://checkstyle.sourceforge.net/config.html#Properties

**Comment by svilenvul** [comment]
Great, I think I have everything that  I needed now to make a single ruleset flexible enough, so I can start working on that.
