### ISSUE TITLE
Measure the Time, Consumed by the Checks

### ISSUE THREAD

**Issue by dstivanov** [openhab/static-code-analysis#319]
As discussed in #212 it will be helpful to measure the build time, that is consumed by each check in the Static Analysis Tool. This way we will be able to decide:

- whether a build time of specific check is worth the benefit;
- whether we need to optimize the check

A very quick research by @tanyatanyatanya discovered the [maven-time-tracker tooling](https://github.com/lptr/maven-time-tracker) by a gradle contributor. However, it looks pretty dusty and it will worth to take a careful look into it.

**Comment by VelinYordanov** [comment]
I think we can use [this](https://github.com/timgifford/maven-buildtime-extension). It's very easy to set up and use - it can measure the time of execution of checkstyle, pmd and findbugs for every module.
