### ISSUE TITLE
Support Java 9 for SAT Tooling

### ISSUE THREAD

**Issue by dstivanov** [openhab/static-code-analysis#325]
As it has been reported by @maggu2810 in [ESH #6199](https://github.com/eclipse/smarthome/issues/6199#issuecomment-421267751 ) there has been problems with the SAT analysis on Java 9 configured build. 

We need to ensure compatibility with Java 9 and address the issue for the next release candidate by testing with Markus' branch as reference.

**Comment by kaikreuzer** [comment]
Java 9 will be EOL end of this month - so I'd suggest to better ensure compatibility with Java 11, which will be out in a few weeks :-)

**Comment by dstivanov** [comment]
I agree, but let's check how far checktyle, findbugs and pmd are in their support :)

**Comment by maggu2810** [comment]
> Java 9 will be EOL end of this month - so I'd suggest to better ensure compatibility with Java 11, which will be out in a few weeks :-)

IMHO it would be great if SAT should work on Java 8, 9, 10 and 11.

Xtext 2.14 seems to be ready for Java 9 and 10.
Xtext 2.14 does not work for Java 11.

So to ensure Java 11 compatibility you have to skip (at a minimum) the model bundles of ESH.

**Comment by dstivanov** [comment]
@lpapazow is now taking a look at the issue and will provide more information as soon as his investigations have results.

**Comment by maggu2810** [comment]
Has there been any progress?

**Comment by lpapazow** [comment]
@maggu2810 , Did you try #332 ?

**Comment by maggu2810** [comment]
No I didn't try it.
My plan has been to not dig into the SAT development at all. :wink: 

AFAIK Xtext and SAT are the parts of the OH build that does not work with Java > 8.
Are there other ones, too?

Xtext 2.17 should be -- if I am informed correctly -- working with Java 8, 9, 10, 11.

So, if we ever bump Xtext the remaining one would be SAT.

**Comment by kaikreuzer** [comment]
@maggu2810 I merged https://github.com/openhab/static-code-analysis/pull/332 as it looks as if in any case won't do any harm - if it makes SAT work on Java9, even better ;-)

Will do a new SAT release now...
