### ISSUE TITLE
Travis build started failing with 'No output has been received in the last 10m0s' error

### ISSUE THREAD

**Issue by lpapazow** [openhab/static-code-analysis#327]
The last two builds from [20 hours ago](https://travis-ci.org/openhab/static-code-analysis/builds/431042873) and [29 days ago](https://travis-ci.org/openhab/static-code-analysis/builds/419605269) are failing with 

> No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received

The Travis configuration hasn't been changed in neither of those two failing PRs and the usual build time is around 3min. 

[30 days ago](https://travis-ci.org/openhab/static-code-analysis/builds/419250735) was the last successful build. Here is the Travis PR [builds history](https://travis-ci.org/openhab/static-code-analysis/pull_requests).

@kaikreuzer  @martinvw, do you have any idea what might have caused the build to fail?

**Comment by lpapazow** [comment]
After I force pushed the same changes again, [the new build](https://travis-ci.org/openhab/static-code-analysis/builds/431429722) passed. Maybe it was a temporary issue.

**Comment by dstivanov** [comment]
I will close the issue. Please feel free to open it with more information, if it happens again.
