### ISSUE TITLE
NPE when ESH-INF not in src/main/resources

### ISSUE THREAD

**Issue by J-N-K** [openhab/static-code-analysis#350]
While reviewing a  new binding I ran into a NPE in checkStyle. The `ESH-INF` directory was located in the project root instead of `src/main/resources`. After moving the files to that directory NPE was gone.

**Comment by wborn** [comment]
Do you know how to reproduce this or do you have a stacktrace?

The tool wasn't even looking in `src/main/resources` it does now with https://github.com/openhab/static-code-analysis/pull/357. My guess is that if there was a NPE in `ESH-INF` the NPE can now occur in `src/main/resources/ESH-INF`. :wink:

**Comment by J-N-K** [comment]
Never seen the issue again. Will re-open if it occurs again and is reproducible.
