### ISSUE TITLE
Check for the Java version in the MANIFEST 

### ISSUE THREAD

**Issue by svilenvul** [openhab/static-code-analysis#36]
Started here : https://github.com/openhab/openhab2-addons/pull/2087#issuecomment-289412622

> FYI: We could add a check for the Java version in the MANIFEST now as well - it is now the very same in ESH and OH2!

See also:

> https://github.com/openhab/static-code-analysis/pull/30#issuecomment-289417745

**Comment by svilenvul** [comment]
@martinvw would you like to work on the check ?

**Comment by martinvw** [comment]
That depends my wife is due today, I have no clue yet how much time this baby is going to consume ;-)

**Comment by martinvw** [comment]
Should be a new class or do you feel that it should be in existing file? I have no idea about the performance of executing a single check.

**Comment by martinvw** [comment]
@svilenvul @kaikreuzer should this be warning or an error?
