### ISSUE TITLE
Check that loggers are non-static loggers and have the correct name

### ISSUE THREAD

**Issue by martinvw** [openhab/static-code-analysis#37]
The overview page suggests that somebody might be working on the following rule:

> As we are in a dynamic OSGi environment, loggers should be non-static, when ever possible and have the name logger.

Is that case and if yes could we make it more visible by assigning this task :-)

**Comment by svilenvul** [comment]
We can add a FindBugs pattern for the first part :

https://github.com/KengoTODA/findbugs-slf4j#slf4j_logger_should_be_non_static

**Comment by martinvw** [comment]
Great and is the base of the findbugs-slf4j-thing already implemented or is it pending somewhere? 

I assume this is then related to #26

**Comment by svilenvul** [comment]
It can be used before #26 is solved, two things are left to be done:
- add the detector that logs this pattern to the [visitors.xml](https://github.com/openhab/static-code-analysis/blob/master/src/main/resources/rulesets/findbugs/visitors.xml);
- openHAB repo should be cleaned up...

**Comment by svilenvul** [comment]
Actually, it's added already - https://github.com/openhab/static-code-analysis/blob/master/src/main/resources/rulesets/findbugs/visitors.xml#L59, so I guess the documentation has to be updated only.

**Comment by martinvw** [comment]
Great!

**Comment by martinvw** [comment]
@svilenvul will you update the README? I'm unsure at which log level it is being logged.

**Comment by svilenvul** [comment]
Yes, this should be ERROR, but I have to check again just to be sure :)

**Comment by svilenvul** [comment]
I have checked it, but is not working as expected.

The message might be ignored from the filter, I have to take a deeper look.
