### ISSUE TITLE
NonNullByDefault for Enums

### ISSUE THREAD

**Issue by fwolter** [openhab/static-code-analysis#389]
Is there a reason why the NonNullByDefault annotation is not checked for Enums? Would you accept a PR to extend the check?

**Comment by wborn** [comment]
I think you've found a bug if there aren't any warnings for adding them to Enums. :wink: 
It would further help to prevent NPEs and usually it's not a lot of work to add them to Enums.

**Comment by fwolter** [comment]
OK, I will file a PR.
