### ISSUE TITLE
Using with Checkstyle extension for VS Code

### ISSUE THREAD

**Issue by SRGDamia1** [openhab/static-code-analysis#391]
Is there any way to get at least the checkstyle portion of the tool to work with the checkstyle extension for VS Code?  https://marketplace.visualstudio.com/items?itemName=shengchen.vscode-checkstyle

I can't figure out how to set up the extension so that it can find the modules needed for the custom rules.

**Comment by Hilbrand** [comment]
Did you try pointing to the raw rules file here: https://raw.githubusercontent.com/openhab/static-code-analysis/master/sat-plugin/src/main/resources/rulesets/checkstyle/rules.xml there are some other files, so it might not work perfectly.

**Comment by SRGDamia1** [comment]
Yes.  It gives errors and won't load the modules:

Module org.openhab.tools.analysis.checkstyle.ParameterizedRegexpHeaderCheck initialization failed. It may be caused by wrong configuraiton or incompatible version.

I tried pointing cloning and compiling this repo and then pointing it to the generated jar (openhab-codestyle-0.11.0-SNAPSHOT.jar) as a module but it gave the same error.

**Comment by wborn** [comment]
Try using the [checkstyle-0.12.0.jar](
https://repo1.maven.org/maven2/org/openhab/tools/sat/custom-checks/checkstyle/0.12.0/checkstyle-0.12.0.jar) as module instead. That JAR contains the custom openHAB check classes. The codestyle JAR is only used by the spotless Maven plugin.
