### ISSUE TITLE
sign goal fails in CI build

### ISSUE THREAD

**Issue by wborn** [openhab/static-code-analysis#410]
Looks like your last minute release changes (https://github.com/openhab/static-code-analysis/commit/36e26fddb153ba8659ac601350b93ad084c431f7) don't work on Jenkins @kaikreuzer.

Thanks for making the release though. :+1: 

See: https://ci.openhab.org/view/All/job/static-code-analysis/22/

```
[INFO] --- maven-gpg-plugin:1.5:sign (sign-artifacts) @ pom ---
gpg: directory '/home/jenkins/.gnupg' created
gpg: keybox '/home/jenkins/.gnupg/pubring.kbx' created
gpg: no default secret key: No secret key
gpg: signing failed: No secret key
...
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-gpg-plugin:1.5:sign (sign-artifacts) on project pom: Exit code: 2 -> [Help 1]
```

**Comment by kaikreuzer** [comment]
Indeed, Jenkins does not (yet) have gpg keys configured, so that the signing fails (which is needed for publishing to Maven Central).
I have created to only sign the artifacts, if a "performRelease" property is set.
