### ISSUE TITLE
Static loggers in (util) classes

### ISSUE THREAD

**Issue by martinvw** [openhab/static-code-analysis#48]
The build fails locally at (among other warnings (https://github.com/openhab/static-code-analysis/issues/47#issuecomment-291108909))
```
[ERROR] ERROR found by findbugs: org.openhab.binding.homematic.type.MetadataUtils.java:
[ERROR] Logger should be non-static field. Change this field (logger) to non-static field.
```
I think we should allow at least classes which are named util to have static loggers. 

Imho it has never been a bad thing to use static methods (even in normal classes) so there also some occurrences where we have other static methods which use logging. It feels strange and bad to refactor those static methods away because of this rule, can we make it a warning instead of an error.

**Comment by martinvw** [comment]
By updating the master it is not a blocker anymore... 

So it's now much less pressing

**Comment by svilenvul** [comment]
OK, this is interesting indeed, I have noticed it once too.

It seems that FindBugs is evaluating the priority based on that, how much issues are found..
