### ISSUE TITLE
Exception if MANIFEST contains "Bundle-Description"

### ISSUE THREAD

**Issue by kaikreuzer** [openhab/static-code-analysis#49]
I had a "Bundle-Description" entry in a manifest of a bundle, which made the checks fail with an exception (similar one as mentioned in https://issues.apache.org/jira/browse/IVY-1438).

Removing this entry made the checks pass correctly.

**Comment by svilenvul** [comment]
I guess the Exception was thrown by the ExportInternalPackageCheck.

**Comment by martinvw** [comment]
Can we upgrade ivy or is there a specific reason we choose 2.3.0

See also https://mvnrepository.com/artifact/org.apache.ivy/ivy/2.4.0
