### ISSUE TITLE
Should every binding be mentioned in features\openhab-addons\src\main\feature\feature.xml

### ISSUE THREAD

**Issue by martinvw** [openhab/static-code-analysis#58]
Since this is a file which is not changed, so no incorrect change but a missing change, its harder to detect in a PR. If it is required we could consider adding a rule for this?

**Comment by kaikreuzer** [comment]
How would you add a rule for that? Checking that every bundle is mentioned in feature.xml? This might not be necessary for every bundle (while for all bindings).

**Comment by martinvw** [comment]
In what cases should a binding be mentioned in feature.xml?

**Comment by kaikreuzer** [comment]
A binding should always be mentioned, so for them, it is ok to check that its id can be found within feature.xml.

**Comment by martinvw** [comment]
Ok so it could be scripted / programmed but it's a little more complex, do you think it should be tested or will the bindings not work at all without it?

**Comment by kaikreuzer** [comment]
Without it, they would not be part of the openHAB distro, which they should be. So yes, testing it makes sense (but it would clearly an openHAB-only rule and not applicable for ESH).

**Comment by martinvw** [comment]
@svilenvul what is a proper way to only make a check active for openhab bindings?

**Comment by svilenvul** [comment]
Good question, at the moment this will be very difficult, as we haven't prepared everything for that. 


You can:

- add the check to the configuration with the following severity property (the default value will be used by the **bundles** Maven profile and the check will not be executed there):
`<property name="severity" value="${checkstyle.yourCheck.severity}" default="ignore" />`

I will : 

- try to add a separate Maven profile for bindings, where we can change the priority by adding a .properties file with the content:
`checkstyle.yourCheck.severity=error
......`

and referring the properties file in the newly created profile.

```
> ....
> <configuration>
>    <checkstyleProperties>relativePath/to/properties.file<checkstyleProperties>
> </configuration>
> .....
```

**Comment by svilenvul** [comment]
@kaikreuzer I would like to create a PR with a new Maven profile for bindings for the static-analysis-tool.

Unfortunately after https://github.com/openhab/openhab2-addons/commit/952d72861f45072c64c18a9d9b60decb3091f193#diff-600376dffeb79835ede4a0b285078036L325 I am not sure where is the pom, where the Maven profiles are defined..

Could you point me to the repository where the  

> `<artifactId>pom-tycho</artifactId>`

is located ?

**Comment by svilenvul** [comment]
I have found it  - https://github.com/openhab/openhab-core/commit/c8486db1a0b4a5804a7b7bbebe4e852e520c0b36#diff-6bbdd8cd058f6cc9364fa4d5501a956b
