### ISSUE TITLE
Make a warning check for scheduleAtFixedRate.

### ISSUE THREAD

**Issue by martinvw** [openhab/static-code-analysis#62]
The coding guidelines state the following:

> For periodically executed jobs that do not require a fixed rate scheduleWithFixedDelay should be preferred over scheduleAtFixedRate.

It sounds like an easy static check, could it be an idea to add an info / warning when you use `scheduleAtFixedRate`?

**Comment by svilenvul** [comment]
When it is included in the guidelines, I guess it is always welcome.

We can ask @kaikreuzer, what does he thinks about this check.

**Comment by kaikreuzer** [comment]
Sure, why not. But it indeed should only be a warning as there are valid use cases for it as well.

**Comment by kaikreuzer** [comment]
Just came across such a case again. So yes, this check is needed 👍

**Comment by lpapazow** [comment]
Hi, I created a check to generate a warning when `scheduleAtFixedRate` method is used.

I ran it on the openhab2-addons repo and it triggered 43 warnings.

**Comment by svilenvul** [comment]
Check merged - https://github.com/openhab/static-code-analysis/commit/9c180bfbef963ba3dcfd1338fe718eea79706b15.

Keeping open to track fixing the found issues.
