### ISSUE TITLE
Move the configuration of the checks out of the Maven plugin

### ISSUE THREAD

**Issue by svilenvul** [openhab/static-code-analysis#7]
The configuration of the checks shouldn't be included in the Maven plugin. At the moment it is stored in the ''src/main/resources/" folder, but should be moved to the repository that is using the plugin.

This will allow having a different configurations for the same check, when using the tool in different builds.

**Comment by kgoderis** [comment]
I am not sure I have missed something but I get on all my files a 

checkstyle	3	3	style	HeaderCheck	Line does not match expected header line of ' * All rights reserved. This program and the accompanying materials'.

**Comment by kaikreuzer** [comment]
@kgoderis: @svilenvul's fixes will only be applied once a new version of the tool is released and referenced in the openHAB build job.

**Comment by kgoderis** [comment]
Maybe this is a rethoric question but I always wondered why some of the repos are not streamed up automatically every night, instead of going through version bumps?
