### ISSUE TITLE
Question: manifest wildcard

### ISSUE THREAD

**Issue by martinvw** [openhab/static-code-analysis#80]
While working on a binding I got the following error:

```
[ERROR] ERROR found by checkstyle: .binding.windcentrale/META-INF/MANIFEST.MF:21 A good approach is to use OSGI-INF/*.xml instead of including the services metadata files separately or using common wildcard. 
```

But the developer used:

```
source.. = src/main/java/
output.. = target/classes
bin.includes = META-INF/,\
               .,\
               OSGI-INF/,\
               ESH-INF/,\
               about.html

```

Is there a reason why that is wrong?

**Comment by martinvw** [comment]
never mind, its referring to the MANIFEST.MF :-(

**Comment by martinvw** [comment]
Here the developer used

```
Service-Component: OSGI-INF/*
```

Same question why is this an error?

**Comment by kaikreuzer** [comment]
This is an error because it would also consider sub-directories and any other (non-XML) file - but what we want to achieve is to only consider xmls in this very folder as the rest will cause exceptions when DS tries to parse stuff that are no DS component declarations.

**Comment by martinvw** [comment]
Ok, thanks!
