### ISSUE TITLE
Add codestyle checks: empty line

### ISSUE THREAD

**Issue by htreu** [openhab/static-code-analysis#81]
There are often empty lines in the code which might be detected automatically:

* after method declaration and before the method-closing-curly-braces:
```
private void doSomething() {

    String myString....

}
```

* after `if`, `for`, `switch`, `case`, `break` statements:
```
if (true) {

    for (;true;) {
    
        switch (value) {

            case 1:

                doSomething();
                break;

        }
    }
}
```

**Comment by svilenvul** [comment]
Thanks for opening this issue.

Do you think [this check](http://checkstyle.sourceforge.net/apidocs/com/puppycrawl/tools/checkstyle/checks/whitespace/EmptyLineSeparatorCheck.html) might be passing for the cases described above ?

Let us hear as well the opinion of @kaikreuzer and @martinvw, if including a check for empty lines is desired ?

**Comment by kaikreuzer** [comment]
I would like it as I see such code often (and am not happy with it then).
But it probably only qualifies for a minor severity level (not breaking the build) :-)

**Comment by htreu** [comment]
From what I see on the first look of EmptyLineSeparatorCheck it is not what I have in mind. The check will also disallow empty lines between header and package dclaration, package and imports, imports and class definition: this is all empty lines which are part of our code style.

**Comment by martinvw** [comment]
Maybe this part is useful any way:

```xml
<module name="EmptyLineSeparator">
    <property name="allowMultipleEmptyLines" value="false"/>
 </module>
```

**Comment by svilenvul** [comment]
@htreu 

It can be configured to check one or more of the following - PACKAGE_DEF, IMPORT, CLASS_DEF, INTERFACE_DEF, STATIC_INIT, INSTANCE_INIT, METHOD_DEF, CTOR_DEF, VARIABLE_DEF.

Could someone define what we exactly need? I guess method definitions definitely and constructors as well?

**Comment by maggu2810** [comment]
> package and imports, imports and class definition

Really? No empty lines between the package and the imports section?
No empty lines between internal imports, framework imports and external ones?
No empty line the imports and the class definition?

I don't know the current OH formatter rules, but this seems not common to me.

**Comment by maggu2810** [comment]
Sorry @htreu ... My reading was incorrect. All fine :wink:

**Comment by htreu** [comment]
I will try a definition: disallow empty lines inside the body on tokens which have a body, but only 1st line and last line, except the _class_ token.
So the first line after `method declaration`, `for`, `if`, `switch`, `case`, `while`, ... and the last line before their closing curly braces: no empty lines.

**Comment by svilenvul** [comment]
I checked again and it seems that this check couldn't be reused - it does exactly the opposite of what is needed (it logs if empty lines are missing). 

In Checkstyle I couldn't find any other check that we can use, so I guess new check has to be implemented.
