### ISSUE TITLE
False positive in EshInfXmlCheck

### ISSUE THREAD

**Issue by kaikreuzer** [openhab/static-code-analysis#85]
On [core.karaf bundle](https://github.com/openhab/openhab-core/tree/master/bundles/org.openhab.core.karaf), I get the prio 1 error

```
Unused configuration reference with uri - system:addons
```

I have no clue what should be wrong and how I could workaround that. @svilenvul can you help? This is rather critical for me :-)

**Comment by svilenvul** [comment]
Yes, I know what is going wrong here - I have added some verifications that when you define a configuration or bridge with uri it is being used in other .xml files in the same bundles, which is mostly true for bindings, but not for other bundles.

It could be added in the exceptions list, but I prefer to remove it at all, it will log false positives too often. wdyt?

**Comment by kaikreuzer** [comment]
If this logic only applies for bindings, you should only activate it for bindings. And even for them, the logic is not always correct, so it definitely must not be a prio 1, but should only be a prio 3 hint to the user that something MIGHT be wrong.

As we have just released 0.0.5 which has this issue: How can I get openhab-core bundles build working? Can I manually override this check for that bundle or do we have to directly release a fixed 0.0.6?

**Comment by svilenvul** [comment]
We should release a new version, the exclude filter is part of the tool.

If you agree I will reduce the priority of the both checks that log false positives, so you can get the build working, and later I will get a more detailed look, how we can avoid the false positives.

**Comment by kaikreuzer** [comment]
Ok, let's do so - let me know as soon as I can do the patch release!

**Comment by svilenvul** [comment]
I think you are ready to go, and what do you think about this [issue ](https://github.com/openhab/static-code-analysis/pull/71#issuecomment-305488715).

**Comment by kaikreuzer** [comment]
> what do you think about this issue .

I guess that can be fixed in the openhab2 bundles.

**Comment by svilenvul** [comment]
Unfortunately Checkstyle doesn't support logging with different levels inside the same check. So I have decided to split the check into to separate checks with different priority:
- one check that only validates the .xml files (error severity);
- one check that tracks the usage of the configurations, bridges (warning severity).
