### ISSUE TITLE
Findbugs can't load jars if they contain special german characters in the path name

### ISSUE THREAD

**Issue by svilenvul** [openhab/static-code-analysis#91]
Started in the [openHAB community forum](https://community.openhab.org/t/static-code-analysis-tool/24489/53). 

The problem is that FindBugs can't find jars that are in directories containing special german characters. I couldn't find an open issue in the [FindBugs repository](https://github.com/findbugsproject/findbugs) or in the [FindBugs Maven plugin](https://github.com/gleclaire/findbugs-maven-plugin) repository, I guess it might be some configuration issue.

FindBugs loads all classes that are referenced in the code that is being analysed. When the path to the file contain special german characters, FindBugs is adding a path containing `?` to the class path and later throws FileNotFoundException.

I have successfully reproduced the issue by checking out the OH2 repository to a subfolder containing special german characters. The Maven log shows the following:

```
....
[DEBUG]   Adding to AuxClasspath ->C:\prj\openHAB\EclipseIDE\git\löwe\openhab2-addons\addons\binding\org.openhab.binding.amazondashbutton\lib\jna-4.2.1.jar
[DEBUG]   Adding to AuxClasspath ->C:\prj\openHAB\EclipseIDE\git\löwe\openhab2-addons\addons\binding\org.openhab.binding.amazondashbutton\lib\pcap4j-core-1.6.6.
jar
[DEBUG]   Adding to AuxClasspath ->C:\prj\openHAB\EclipseIDE\git\löwe\openhab2-addons\addons\binding\org.openhab.binding.amazondashbutton\lib\pcap4j-packetfacto
ry-static-1.6.6.jar
...
...
...
     [java] JVM args ignored when same JVM is used.
     [java] The following errors occurred during analysis:
     [java]   File not found: filesystem:C:\prj\openHAB\EclipseIDE\git\l?we\openhab2-addons\addons\binding\org.openhab.binding.amazondashbutton\lib\jna-4.2.1.ja
r
     [java]   File not found: filesystem:C:\prj\openHAB\EclipseIDE\git\l?we\openhab2-addons\addons\binding\org.openhab.binding.amazondashbutton\lib\pcap4j-core-
1.6.6.jar
     [java]   File not found: filesystem:C:\prj\openHAB\EclipseIDE\git\l?we\openhab2-addons\addons\binding\org.openhab.binding.amazondashbutton\lib\pcap4j-packe
tfactory-static-1.6.6.jar
     [java] The following classes needed for analysis were missing:
     [java]   org.pcap4j.core.PacketListener
     [java]   org.pcap4j.core.PcapHandle
     [java]   org.pcap4j.packet.Packet
     [java]   org.pcap4j.packet.EthernetPacket
     [java]   org.pcap4j.packet.EthernetPacket$EthernetHeader
     [java]   org.pcap4j.core.PcapNetworkInterface$PromiscuousMode
     [java]   org.pcap4j.core.BpfProgram$BpfCompileMode
     [java]   org.pcap4j.packet.namednumber.ArpOperation
     [java]   org.pcap4j.packet.namednumber.UdpPort
     [java]   org.pcap4j.packet.ArpPacket
     [java]   org.pcap4j.packet.ArpPacket$ArpHeader
     [java]   org.pcap4j.packet.UdpPacket
     [java]   org.pcap4j.packet.UdpPacket$UdpHeader
     [java]   org.pcap4j.core.PcapAddress
     [java]   org.pcap4j.core.PcapNetworkInterface
     [java]   org.pcap4j.core.Pcaps
     [java]   org.pcap4j.util.MacAddress
     [java]   org.pcap4j.core.PcapNativeException
     [java]   org.pcap4j.core.NotOpenException
     [java]   org.pcap4j.core.BpfProgram
     [java] Missing classes: 18
     [java] Analysis errors: 3
...


```

**Comment by svilenvul** [comment]
What I have done so far is the following - changed the locale of my Windows machine (Region and Language -> Administrative -> Change system locale..  ) to German. 

I have tried to execute Maven with the following command line args:
```
-Dfile.encoding=UTF-8
-Dproject.build.sourceEncoding=UTF-8
-Dproject.reporting.outputEncoding=UTF-8
```

**Comment by svilenvul** [comment]
I would appreciate any help with this issue :)

**Comment by svilenvul** [comment]
Please note that when these ```FileNotFoundException```s are logged, the build continues executing (they may only affect the report produced by FindBugs).

**Comment by martinvw** [comment]
I think this is not something we can solve however the other issue is https://community.openhab.org/t/static-code-analysis-tool/24489/56 more likely to be related to something we can fix..

**Comment by svilenvul** [comment]
Do you mean this one? 
```
[ERROR] Failed to execute goal org.openhab.tools:static-code-analysis:0.0.6:findbugs (default) on project org.openhab.binding.tankerkoenig: Unable to execute mojo: Invalid byte 2 of 4-byte UTF-8 sequence. -> [Help 1]
```

**Comment by martinvw** [comment]
Yes

**Comment by martinvw** [comment]
It was caused by the umlaute in the pom.xml which ended up in the findBugs.XML but it might also just be a problem with Findbugs itself.

**Comment by svilenvul** [comment]
OK, continues in #93

**Comment by svilenvul** [comment]
I wonder if the issue is still present after moving to SpotBugs - https://github.com/openhab/static-code-analysis/commit/89e04dd14b96925553de0cef451d860091f98ef4

**Comment by svilenvul** [comment]
Yes, it is sill the same situation - I have tested it.

**Comment by svilenvul** [comment]
Issue opened in the SpotBugs repository - https://github.com/spotbugs/spotbugs/issues/420
