### ISSUE TITLE
SAT build fails with error in findBugs.xml

### ISSUE THREAD

**Issue by svilenvul** [openhab/static-code-analysis#93]
Log: 

```
[java] Missing classes: 24
[java] Analysis errors: 182
[INFO] Done FindBugs Analysis....
[Fatal Error] findbugsXml.xml:2:145: Invalid byte 2 of 4-byte UTF-8 sequence.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 39.539 s
[INFO] Finished at: 2017-06-09T23:31:55+02:00
[INFO] Final Memory: 64M/578M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.openhab.tools:static-code-analysis:0.0.6:findbugs (default) on project org.openhab.binding.tankerkoenig: Unable to execute mojo: Invalid byte 2 of 4-byte UTF-8 sequence. -> [Help 1]
```

 martinvw commented 
> It was caused by the umlaute in the pom.xml which ended up in the findBugs.XML but it might also just be a problem with Findbugs itself.

**Comment by svilenvul** [comment]
@martinvw 

Do you thing it is related to https://github.com/gleclaire/findbugs-maven-plugin/issues/18 ?

If yes, an update to findbugs maven plugin 3.0.4 should be enough.

**Comment by martinvw** [comment]
> Do you thing it is related to gleclaire/findbugs-maven-plugin#18 ?

Not unlikely there it is with message and we have with project name but the symptoms and most likely the cause might be the same 

> If yes, an update to findbugs maven plugin 3.0.4 should be enough.

I doubt it because it should have been solved in

> gleclaire modified the milestone: findbugs-maven-plugin-3.0.2 on Aug 14 2015

But a user reports:

> I still have this issue with encoding 8859-2 in versions 3.0.2 and 3.03.

So we could maybe report our own findings there as well :-)

**Comment by svilenvul** [comment]
The new version definitely shows some improvements when I tested it on my local build here, so I think anyway it is good to update it.

**Comment by svilenvul** [comment]
Could it be http://gleclaire.github.io/findbugs-maven-plugin/check-mojo.html#outputEncoding ?

From what I have read in the [javadoc](https://github.com/gleclaire/findbugs-maven-plugin/blob/master/src/main/groovy/org/codehaus/mojo/findbugs/FindBugsMojo.groovy#L221):  

> The file encoding to use when creating the HTML reports. If the property <code>project.reporting.outputEncoding</code> is not set, the platform default encoding is used."

**Comment by martinvw** [comment]
Is this closed now with the two PR's

**Comment by svilenvul** [comment]
I am not hundred percent sure, we can close it, and if the problem occurs again we can reopen it ?
